### ISSUE TITLE
Question: running rulesets in sequence.

### ISSUE THREAD

**Issue by saharati** [FluentValidation/FluentValidation#1278]
### System Details

- FluentValidation version: 8.6.0
- Web Framework version: .NET Core 3.0 Web API

### Issue Description

Hello everyone, I checked through the documentation multiple times and didn't quite find an answer so i'm sorry if its something too obvious :)
What I want to do is run the default rules, and only if all of them pass, run a specific ruleset.
This is how my code looks like atm:
```
var result = await validator.ValidateAsync(request);
if (result.IsValid)
    result = await validator.ValidateAsync(request, ruleSet: "DbChecks");
```

Was just wondering if this is really how I should go about it, or is there a better way to achieve this?

Edit: for more clarification I want to do something like this:
https://stackoverflow.com/questions/21896249/conditionally-executing-rule-with-fluentvalidation-for-net
But without having to duplicate code as suggested in the answer...

Or even like this:
https://github.com/JeremySkinner/FluentValidation/issues/65
But with more than 1 rule, e.g. I want to check if a confirmPassword field equals the password field only if both confirmPassword and password fields aren't empty.

**Comment by derldalfor100** [comment]
Interesting, I've the same problem, someone knows?

**Comment by JeremySkinner** [comment]
The usual way of doing this is the way recommended in the stackoverflow answer that you linked to. Having duplication here is not generally considered a bad thing - it's explicit and clear what's going on. 

Your example code is also a perfectly valid way of doing this. If that's working for you then I'd suggest continuing to do it.

**Comment by saharati** [comment]
@JeremySkinner 
Well thanks for the answer, hopefully there would be an option to do it in the future, because it should be possible afaik and the current way of doing it is not clean and produces duplicated code :/

Something like accessing the validation context within the When function, my knowledge in c# is not all that great but I guess something along the lines:
```
RuleFor(x)...
RuleFor(y)...
RuleFor(z).When(someContext => someContext.ruleFor[x].Passed && someContext.ruleFor[y].Passed)
```

That could be a good way of doing it if it would be possible, without actually having to repeat what x and y rules check for...

**Comment by JeremySkinner** [comment]
Syntactically that wouldn't be feasible for 2 reasons:
- The validation context does not contain the state of which rules failed. 
- The order of rule execution is not guaranteed (so you can't assume that x and y have already been executed at the time z executes). 

If we were going to add this feature, the way to do this would be an extension of the [dependent rules syntax](https://fluentvalidation.net/start#dependent-rules).  As you've already seen, this allows rules to be executed only if a specific preceding rule executes first:

```csharp
RuleFor(x => x.Surname).NotNull().DependentRules(() => {
  RuleFor(x => x.Forename).NotNull();
});
```

...what we could do is look at adding a top-level `DependentRules` method (similar to the top-level `When` method) that allows a block of rules to be defined:

```csharp
DependentRules(() => {
  RuleFor(x => x.Surname).NotNull();
  RuleFor(x => x.SomethingElse).NotNull()
},() => {
    RuleFor(x => x.Forename).NotNull();
});
```

However personally I find this to be extremely unclear as to what's happening, and that this is much nicer (despite the duplication):

```csharp
RuleFor(x => x.Surname).NotNull();
RuleFor(x => x.SomethingElse).NotNull();
RuleFor(x => x.Forename).NotNull().When(x => x.Surname != null && x.SomethingElse != null);
```

You seem to think that duplication is a bad thing, but it really isn't. I'm a firm believer that duplication is perfectly acceptable (and preferable) when it makes the resulting code easier to understand (which is why I'm generally against using DependentRules in general). 

If this is functionality that the community wants then I'd be open to adding it, but I would strongly recommend not going down this route. I'll re-open this issue for now so others can feed back too. If it gets lots of buy-in then I can look at it for 9.0.

**Comment by JeremySkinner** [comment]
No further feedback received; closing.
