### ISSUE TITLE
Default implementations in interfaces - code coverage

### ISSUE THREAD

**Issue by jzabroski** [FluentValidation/FluentValidation#1322]
Hi Jeremy,

With the introduction of InlineValidator, we no longer have to subclass AbstractValidator in order to create a validator.  This seems parsimonious with C# 8.0 allowing [default interface methods](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/default-interface-methods-versions).

For example, I can imagine something like:

```c#
public interface IHasCusip
{
  string CUSIP {get; set;}
  InlineValidator Validator => new InlineValidator<IHasCusip>() {
      v => v.RuleFor(x => x.CUSIP).NotEmpty(),
      v => v.RuleFor(x => x.CUSIP).Must(InstrumentValidation.HaveValidCusip).When(x => !string.IsNullOrWhitespace(x.CUSIP))
    };
}
```

But... I get a compilation error when I want to "inject" this InlineValidator into another AbstractValidator's constructor via SetValidator.  I'm not sure why.  It could be a bug in the .NET type system, or simply a "hole" in FluentValidation's generics.  I had spent an hour writing up a .NET Fiddle with a full repro, but when I went to save, it crashed...

**Comment by JeremySkinner** [comment]
Hi, I'm afraid I can't help you unless you provide the error message you're getting along with steps to reproduce.

**Comment by jzabroski** [comment]
https://dotnetfiddle.net/ATkeG4

Compilation error (line 136, col 24): Cannot convert lambda expression to type 'IPropertyValidator' because it is not a delegate type

**Comment by JeremySkinner** [comment]
Your type declarations are mismatched. This is the code you have:

```csharp
var builder = new FluentValidation.Internal.RuleBuilder<Equity, string>(FluentValidation.Internal.PropertyRule.Create<Equity, string>(x => x.CUSIP),null);
builder.SetValidator((IHasCusip person) => person.Validator);
```

You've created a `RuleBuilder<Equity, string>`, so `SetValidator` will take an argument of type `Func<Equity, IValidator<string>>` , but you're passing in a `Func<IHasCusip, IValidator<IHasCusip>>` - these are completely different types that aren't assignable in any way, so C# will correctly generate a compile error. This isn't a bug in the .NET type system, or a "hole" in FluentValidation's generics, this is the compiler doing what it's supposed to, because you're passing in a value that simply isn't valid and can't be compiled.  

But secondly, you shouldn't be instantiating a RuleBuilder like this - rule construction is done by calling the `RuleFor` method. Here's what you should be doing:

```csharp
public class EquityValidator : AbstractValidator<Equity>
{
	EquityValidator()
	{ 
		RuleFor(equity => equity).SetValidator(equity => ((IHasCusip)equity).Validator);
	}
}
```

**Comment by jzabroski** [comment]
That worked, thank you.
