### ISSUE TITLE
Add Built-In URI Validation

### ISSUE THREAD

**Issue by ryanelian** [FluentValidation/FluentValidation#1329]
### System Details

- FluentValidation version: -
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): -

### Issue Description

URL can be validated fast and safely using the convenience .NET method:

```cs
        public bool ValidateUri(string uri)
        {
            // just so the validation passes if the uri is not required / nullable
            if (string.IsNullOrEmpty(uri))
            {
                return true;
            }
            return Uri.TryCreate(uri, UriKind.Absolute, out _);
        }
```

FluentValidation should have a rule for this:

```cs
RuleFor(Form.SomeUri).IsValidUri(UriKind.RelativeOrAbsolute);
```

This allows users of [`[UrlAttribute]`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.urlattribute?view=netframework-4.8) to migrate to your library without rewriting the validator.

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion. 

We're not currently planning on including any further validators in the core library due to the maintenance overhead that they add, as well as the large undertaking to get error messages translated into [all the supported languages](https://github.com/FluentValidation/FluentValidation/tree/master/src/FluentValidation/Resources/Languages)

However, FluentValidation supports the extensibility points that allow you to [add custom validators yourself](https://docs.fluentvalidation.net/en/latest/custom-validators.html) in several different ways, which you can then include in your own project. Additionally, if you think such a feature would be useful to the community then you could always release it as a separate Nuget package that extends FluentValidation. 

In this particular case, the logic is so small that it may not even need a custom validator - you can just embed the logic in a call to `Must`:

```csharp
RuleFor(x => x.SomeUri).Must(uri => Uri.TryCreate(uri, UriKind.Absolute, out _).When(x => !string.IsNullOrEmpty(x.SomeUri));
```

...which you could wrap in an extension method if you like (see custom validator links above which explain how to do this).

Hope that helps.

**Comment by ryanelian** [comment]
That is quite unfortunate. 

I am using a `.Must` to write that but I thought this particular validator fits right in the core library due to its relative simplicity and due to the fact `[UrlAttribute]` for Data Annotations exists.

AFAIK you are only missing this particular validator to reach parity against the Data Annotation validator.

| Data Annotation  | Fluent |
| ------------- | ------------- |
| CompareAttribute  | Equal  |
| CreditCardAttribute  | Credit Card  |
| EmailAddressAttribute | Email |
| FileExtensionsAttribute  | Matches  |
| MaxLengthAttribute  | MaxLength |
| MinLengthAttribute  | MinLength  |
| PhoneAttribute  | Matches `^[0-9]+$` |
| RangeAttribute  | Less / Greater Than Or Equal |
| RegularExpressionAttribute | Matches |
| RequiredAttribute  | NotEmpty |
| StringLengthAttribute | MinLength MaxLength  |
| UrlAttribute | THIS FEATURE REQUEST |

**Comment by JeremySkinner** [comment]
I understand that to you this might appear to be a simple feature request, but I'd ask you to please look at this from the maintainer's perspective. Adding even a small new validator requires the following:

- Writing the feature itself
- Writing tests
- Writing the documentation
- Translating the default error messages into [35 different languages](https://github.com/FluentValidation/FluentValidation/tree/master/src/FluentValidation/Resources/Languages)
- Making a commitment to provide support and answer questions on the feature for the foreseeable future

This is a large time commitment for something I do in my (limited) free time, which is why I am very careful about accepting new features. It is far more useful to have a solution that is extensible than it is to have something that tries to cover every possible use case. This is precisely why FluentValidation is designed to be extensible- it offers a useful set of default rules that cover some common scenarios, but the power is in the extensibility mechanism, allowing you to use FluentValidation's building blocks to do your own thing when working with a use case that's not covered by the defaults.

As I mentioned previously, FluentValidation provides several ways to write your own custom validation logic - if you don't want to duplicate the logic using `Must`, then you can write the logic in a single, reusable place within your solution. This would solve the issue for your particular project, and if you strongly feel that this is a feature that the whole community needs (beyond just your project), and you believe it's worth the time and effort to develop and support include this, then please be my guest and release it as an extensibility package for FluentValidation. 

This doesn't mean to say that I'll never accept new default validators, but it requires thought, planning, prioritizing and the time to do these things. From a priority perspective, most of my time goes into:
- Answering questions and providing support on this issue tracker
- Keeping up to date with .NET Core releases (which have a large impact on FluentValidation and require a significant time investment)
- Bug fixes 
I'm afraid that features that can already be implemented using the existing extensibility points are not going to be high up the priority list. 

Thanks for understanding.
