### ISSUE TITLE
Better handling of indexers in TestHelper

### ISSUE THREAD

**Issue by JeremySkinner** [FluentValidation/FluentValidation#1339]
At the moment, indexers aren't supported in the TestHelper extensions that accept lambdas, only the string-based overloads. Update the lambda-based overloads to support them too. 

The simplest thing to do would be to call ToString on the expression tree and then manipulate the string:
- Remove the `=>` and anyting before it
- Rewrite indexer calls to `get_Item(0)` to `[0]`
- Would mean having to explicitly write special cases for any other weird stuff that people might put inside expression trees (which would get very complicated)

Other option would be to use an expression-parsing library like https://github.com/AgileObjects/ReadableExpressions or https://github.com/zspitz/ExpressionTreeToString but this would mean taking a package dependency, and I'm not really sure it's worth brining along a whole other library whenever FV is installed just for the TestHelper.

**Comment by jzabroski** [comment]
Can you break out TestHelper into TestHelper.Supercharged as an external lib?  Then people can choose to whether to take the dependency.

As far as manipulating expression trees goes, I found @fsoikin's erecruit.Expr to be very useful/powerful.  However, it sounds like your use case is to pretty print the expression, rather than manipulate it?

**Comment by JeremySkinner** [comment]
No, I don't see any benefit to moving this to a separate library. The test helpers are tiny. An additional dependency doesn't serve any purpose here. 

I've already implemented the necessary expression tree manipulation in the PR #1340.
