### ISSUE TITLE
Disable ASP Model Validation

### ISSUE THREAD

**Issue by TorreyGarland** [FluentValidation/FluentValidation#1341]
Hi, I am currently using FluentValidation.MVC4 signed, version 5.1.0.0 for an MVC 5 project at work.

I need to perform remote validation for a model using AJAX.  This is not the issue.

The problem is that the when it accesses a controller method specific for validation of a subset of properties (for example: Name, Age - validates only to ensure there are no duplicates in the database), the existing validator configured validates all rules (for example: Name, Age, Height, Width, StepBrothersFirstName - validates everything).

Upgrading to a new version of fluent validation is possible, but we are no where near to switching to MVC Core yet.

Is there a way to disable validation on an ActionResult method-by-method basis.  The trouble I run into now is that:

- trying an interceptor with the CustomizeValidateAttribute doesn't seem to work.
- trying a ruleset with the CustomizeValidateAttribute seems like I am replicating a lot of code, doesn't feel so "fluenty"

I would prefer to bypass FluentValidation model validation and use a custom service for validation.

Any ideas?

**Comment by JeremySkinner** [comment]
Hi there,

FluentValidation 5 is a very old unsupported version and doesn’t contain any mechanism for skipping validation for a specific model. This is largely due to limitations in MVC’s validation api. If you’re not able to upgrade to a newer version then I can only see 3 options:

1. Disable all automatic validation for that specific model type, by removing its [Validator] attribute. Anywhere that relies on automatic validation form this model type would need to be changed to perform manual validation. 

2. Override your Validator’s Validate method, access HttpContext.Current to check the current url/route and immediately return if it’s the action you want to skip. This is probably the simplest solution, but is a bit hacky. 

3. you could take the source code for the FluentValidationModelValidator provider and modify it to to support some kind of mechanism to indicate that validation should be skipped in some circumstances. You could try and replicate the behaviour of the Skip property on the CustomizeValidatorAttribute that’s part of more modern versions of FV.

**Comment by TorreyGarland** [comment]
Option #3 is working.

Thanks for the prompt and and thorough response!
