### ISSUE TITLE
[Question]How to write validator for collection model binding in ASP.NET Core?

### ISSUE THREAD

**Issue by lamLeX** [FluentValidation/FluentValidation#1344]
### System Details

- FluentValidation version: FluentValidation.AspNetCore 8.6.2
- Web Framework version: ASP.NET Core 2.2

### Issue Description
Asp.Net Core support collection binding like this 
```C#
[ApiController]
public class ClassroomController : ControllerBase {
	
	[HttpPost]
	public IActionResult CreateFromStudent([FromBody]IEnumerable<Student> students) {
                  // Code for create Classroom
	}
}
```
Let say my `Student` will look like this
```C#
public class Student 
{
    public Teacher Teacher{get;set;}
    //Some additional properties
}
```
Now want to validate that all students in `IEnumerable<Student> students` has the same teacher.
The documentation for Collection validator https://docs.fluentvalidation.net/en/latest/collections.html seems not cover this scenario.
How do I write a validator to accomplish this without creating a wrapper complex type with the collection as a property?

**Comment by JeremySkinner** [comment]
Hi, if you enable Implicit Child Validation then asp.net will do this automatically for you: https://docs.fluentvalidation.net/en/latest/aspnet.html#implicit-vs-explicit-child-property-validation This will recursively discover and execute validators for collection elements and also child properties. 

Note that this isn’t enabled by default as it means that `SetValidator` can’t be used anymore. 

Alternatively if you don’t want to enable this the. I believe you could just create a validator for the entire collection (eg `AbstractValidator<List<Student>>`), but you’d need to experiment with this

**Comment by lamLeX** [comment]
Hi, 
Actually, the thing I want to validate is on the collection level, not the child level.

I have tried writing `AbstractValidator<List<Student>>` and `AbstractValidator<IEnumerable<Student>>` but I'm stuck at the LINQ expression because I don't know how to construct a valid one to pass to `RuleFor()`

Here is my example Rule setup
```C#
RuleFor(students => /*Neither IEnumerable<T> nor List<T> expose the underlying collection */)
     .Must(students => students.Distinct(x => x.Teacher).Count() = 1);
```

**Comment by JeremySkinner** [comment]
You’d need to use a parameter expression pointing back to itself, ie `RuleFor(x => x).Must(...)`

**Comment by lamLeX** [comment]
Awesome, the self-pointer expression works.
Thank you very much.

**Comment by lamLeX** [comment]
Hi @JeremySkinner ,
Although the code is compiled for the Validator and registered in the DI, the validation is not triggered upon model binding validation stage. 
I observed this behavior by setting the breakpoint in the delegate passed to `Must()`
![image](https://user-images.githubusercontent.com/4281894/76117857-7f663700-5fa1-11ea-8e3b-b2b5563545a7.png)

The code passed the validation and reached the code thats run after validation middleware although the input is invalid
![image](https://user-images.githubusercontent.com/4281894/76117988-ca804a00-5fa1-11ea-8521-4b4972de227c.png)

After some debugging and troubleshooting, I found out that my model is actually type of `List<T>` instead of `IEnumerable<T>`. Due to the nature of Microsoft DI, it only matches the exact type. The `FluentValidationClientModelValidatorProvider` only have `IValidator<IEnumerable<T>>` instead of `IValidator<List<T>>`; hence, it couldn't find my validator for `List<T>`

I wonder if we could do anything in `ServiceProviderValidatorFactory.CreateInstance()` to accommodate this scenario?

**Comment by JeremySkinner** [comment]
Hi, this isn't something that should be done in the ServiceProviderValidatorFactory, but rather is something you should set up explicitly with your container registrations. 

You're correct that if your action parameter is an `IEnumerable<T>`, then MVC will instantiate a `List<T>` - this is because MVC's model binding process doesn't actually know your intent when you specify an interface as an action method parameter, so it guesses and creates a List, which is the type that's then passed into the validation infrastructure.

Personally I'd always recommend using explicit concrete types as action method parameters because of this (ie explicitly specify either `List<T>` or `T[]`). If your validator type directly matches the type of the action parameter (ie both are using List), then this will all just work without any issues. 

However if you want to continue to use IEnumerable in your validator then you'll need to be explicit about this in your container registration. The `T` in `AbstractValidator<T>` is contravariant, so you should be able to register a mapping with the container for `IValidator<List<Student>>` to `StudentValidator` (where `StudentValidator` inherits AbstractValidator<IEnumerable<T>>`). If you set this up with an explicit call to `services.AddTransient` in your application startup routine then I believe this should work fine.

**Comment by lamLeX** [comment]
I see, it's fair.
I'll go with explicit registration solution for now.
