### ISSUE TITLE
DisplayNameAttribute localization of {PropertyName}

### ISSUE THREAD

**Issue by pauldbentley** [FluentValidation/FluentValidation#1374]
### System Details

- FluentValidation version: 8.6.2
- Web Framework version: netcoreapp3.1, Microsoft.NET.Sdk.Web

### Issue Description
Should the error messages localize the {PropertyName} from the [DisplayName] attribute?

In my application, the error messages are correctly localizing, but the {PropertyName} isn't:

`'The value' ne doit pas être vide.`
`'The value' doit contenir entre 2 et 10 caractères.`

Does this look like I'm missing something in my setup?

#### My class and validator

```
public class Command
{
    [DisplayName("The value")]
    public string Value { get; set; }
}

public class Validator : AbstractValidator<Command>
{
    public Validator()
    {
        RuleFor(e => e.Value)
            .NotEmpty()
            .Length(2, 10);
    }
}
```

#### My Razor code
```
<div class="form-group">
    <label asp-for="Input.Value"></label>
    <input asp-for="Input.Value" class="form-control" />
    <span asp-validation-for="Input.Value" />
</div>
```

#### The ResX
```
<data name="The value" xml:space="preserve">
    <value>La valeur</value>
</data>
```

#### The rendered output

```
<div class="form-group">
	<label for="Input_Value">La valeur</label>
        <input class="form-control" type="text" data-val="true" data-val-length="&#x27;The value&#x27; doit contenir entre 2 et 10 caract&#xE8;res." data-val-length-max="10" data-val-length-min="2" data-val-required="&#x27;The value&#x27; ne doit pas &#xEA;tre vide." id="Input_Value" name="Input.Value" value="" />
        <span class="field-validation-valid" data-valmsg-for="Input.Value" data-valmsg-replace="true" />
</div>
```

So somewhere it's not picking up `La valeur` when localizing the error messages.

Thanks

**Comment by JeremySkinner** [comment]
Hi, no this isn't supported I'm afraid.

FluentValidation's recommended mechanism for localizing the property name is to use the `WithName` method (the overload that takes a func). This can either be used with strongly-typed resource wrappers, or with .NET Core's IStringLocalizer. [Please see this page in the documentation](https://docs.fluentvalidation.net/en/latest/localization.html) (the examples use WithMessage, but the same applies to WithName too). 

For some background information: in the past we have historically also supported pulling the property name from the `DisplayAttribute`, but unfortunately with the changes to how localization works for .NET core this is no longer possible. FluentValidation 9 actually removes default support for the DisplayAttribute because of this.

**Comment by pauldbentley** [comment]
Hey @JeremySkinner thanks for the quick response and the background information.  I knew I was missing something but just couldn't quite figure it out.  Using `WithName` and injecting `IStringLocalizer` has worked.  Thanks
