### ISSUE TITLE
Question: How to Add Fluent Validation without mvc dependency

### ISSUE THREAD

**Issue by mnisha** [FluentValidation/FluentValidation#1377]
- FluentValidation version: 9.0.0 preview4
- Rest API .net core 3.1 

Hello,
I'm trying to add FluentValidations without using the Add.Mvc() method, is it possible?
How can I register all validators in StartUp this way?

I installed only the FluentValidation package, and tried to add validators using 
services.AddValidatorsFromAssemblyContaining<TestValidator>();
bust seems I'm missing something because ModelState.IsValid always true.

I looked everywhere for an answer and could not find detailed answer.

Thank you

**Comment by JeremySkinner** [comment]
Hello. The automatic validation support is an extension for MVC. You *must* call AddMvc first, as per the documentation.

**Comment by mnisha** [comment]
So I also have to install FluentValidation.AspNetCore?

**Comment by JeremySkinner** [comment]
Yes. Can I suggest you read the documentation? This is covered there https://docs.fluentvalidation.net/en/latest/aspnet.html

**Comment by mnisha** [comment]
Thanks I already read it.
I saw a comment in [this](https://github.com/FluentValidation/FluentValidation/issues/985)
and I did not understand how can I use FluentValidation without mvc

Now I understand that I have to install both FluentValidation & FluentValidation.AspNetCore and call AddMvc().AddFluentValidation

**Comment by JeremySkinner** [comment]
> I saw a comment in this

The issue you linked to is a different scenario. In that issue, the user didn't want any kind of automatic validation, and only wanted to use the validators manually (ie by directly calling the `Validate` method on each validator instance). ModelState will not be automatically populated with this approach, because the FluentValidation MVC integration is not enabled. 

That is different to what you were asking, as you still wanted ModelState to be populated, which does require the automatic MVC integration.
