### ISSUE TITLE
Disable automatic server-side validation but keep auto client validation (MVC5)

### ISSUE THREAD

**Issue by jsabrooke** [FluentValidation/FluentValidation#1379]
### System Details

- FluentValidation version: 8.6.1
- Web Framework version: MVC 5

### Issue Description
Hi, please could you let me know if it's possible to disable the automatic server-side validation but _keep_ auto client validation with MVC5, so that I can then perform the server-side validation manually?

I've got the automatic validation working for both client-side and server-side, however, I'd like to be able to perform further manual initialisation on the view model following a post, before it gets validated at server side. Specifically at the moment, it's for when fields are disabled on the front end, in which case they don't get posted (which is correct as I want them to be resolved from DB, not the posted form). I could set up more complex rules to not validate them when I expect them to not be posted, and then do some separate validation of them later, but I'd rather keep the rules simpler and do that validation all in one go if possible. I think I'll probably find other reasons for this later as well as just disabled fields.

It would also give me more flexiblity if I find in the future that I want to be able to specify rulesets for server-side validation. I've found that I can't do this with the automatic validation (unless AbstractValidator.Validate was virtual, but this isn't the main thing at the moment). 

I can think of an unpleasant workaround to disable the auto server validation only, but I'd rather not do it :-).

I can see that it might be possible for .NET Core (https://github.com/FluentValidation/FluentValidation/issues/412), but that part of your code looks very different from the MVC5 equivalent.

Thanks very much in advance for your help!
James

**Comment by JeremySkinner** [comment]
Hi, she validation infrastructure between MVC5 and ASP.NET Core is pretty different. In MVC5, the server/clientside validation API is much more tightly coupled. You can still do this though:

- Create a class that inherits from `FluentValidationModelValidatorProvider`
- Override the `GetValidatorsForModel` method and change it so that it always returns an empty collection
- Change your application startup code to use your new provider class, rather than the FV provider:

```csharp
// Do this...
DataAnnotationsModelValidatorProvider.AddImplicitRequiredAttributeForValueTypes = false;
ModelValidatorProviders.Providers.Add(new MyCustomProvider());
// Instead of FluentValidationModelValidatorProvider.Configure()
```

> It would also give me more flexiblity if I find in the future that I want to be able to specify rulesets for server-side validation

You can use Validator Interceptors to customize the ASP.NET server-side validation process ([see this page in the docs](https://docs.fluentvalidation.net/en/latest/mvc5.html#validator-interceptors))

> unless AbstractValidator.Validate was virtual

It is virtual (the overload that takes a ValidationContext is the only one that is - this is the main method, and all the others pass through this). If you do override this make sure you always override ValidateAsync too to keep the behaviour in sync.

Also in case you weren't aware, I will just point out that FluentValidation's MVC5 integration is deprecated, and will be completely unsupported once FluentValidation 9 is released.

**Comment by jsabrooke** [comment]
Brilliant! Thank you so much!

Exactly what I wanted. I couldn't see how to use my own implementation of `FluentValidationModelValidatorProvider` at first, and I thought that if I did work that out, I would then end up breaking the client validation as well. Now I see that `GetValidatorsForModel` is only used for the server-side. 

> It is virtual (the overload that takes a ValidationContext is the only one that is - this is the main method, and all the others pass through this).

Ah yeah sorry, I was looking at overriding `public ValidationResult Validate(T instance)` so I could use  the extension 
```
public static ValidationResult Validate<T>(
    this IValidator<T> validator,
    T instance,
    IValidatorSelector selector = null,
    string ruleSet = null)
````
I guess I should have looked at the virtual one too and worked something else out (or looked into the interceptors) Doesn't matter now anyway as I don't need to do that now.

> Also in case you weren't aware, I will just point out that FluentValidation's MVC5 integration is deprecated, and will be completely unsupported once FluentValidation 9 is released.

Thanks for mentioning, I hadn't noticed that. Maybe not the best time to just start integrating it into .NET Framework projects... I can just add this to my list of reasons to use to convince those in charge that we should upgrade a few of our older (but regularly updated) projects to .NET Core! :-)

Thanks again!
