### ISSUE TITLE
Problem with @inject StringLocalizer

### ISSUE THREAD

**Issue by Foizman** [FluentValidation/FluentValidation#1384]
Hi there,

I want to add your component to an existing .NETCore Blazor App project. There are huge resource-files for English and German, localization works perfectly so far within the App. To do this, I use `@inject IStringLocalizer`. Please have a look at this working example:

`@page "/test"`
`@layout MainLayout`
`@using FluentValidation`
`@using Microsoft.Extensions.Localization`
`@inject IStringLocalizer<Pages.Ressources.DefaultTranslations> LangBasic`
`<EditForm Model="@customer">`
`    <FluentValidator Validator="myvalidator"></FluentValidator>`
`    <p>This is a resx-test: @LangBasic["Forename"]</p>`
`    <p>`
`        <InputText @bind-Value="@customer.Forename" />`
`        <ValidationMessage For="@(() => customer.Forename )" />`
`        <button type="submit">Submit</button>`
`    </p>`
`</EditForm>`
`@code`
`    {`
`    public class CustomerValidator : AbstractValidator<Customer>`
`    {`
`        public CustomerValidator()`
`        {`
`            RuleFor(x => x.Forename).NotEmpty();`
`        }`
`    }`
`    public class Customer`
`    {`
`        public string Forename { get; set; }`
`    }`
`    CustomerValidator myvalidator = new CustomerValidator();`
`    Customer customer = new Customer();`
`}`

This rule works (see above): 
`RuleFor(x => x.Forename).NotEmpty();`

This works, too: 
`RuleFor(x => x.Forename).NotEmpty().WithName("test");`

This doesn't: 
`RuleFor(x => x.Forename).NotEmpty().WithName(@LangBasic["Forename"]);`

Any ideas, how to inject the forename-translation `@LangBasic["Forename"]` from the resource-files into your rule within this setup? Studied all your documentation for hours, haven't got it running.

Cheers,
Volker

**Comment by JeremySkinner** [comment]
Hi there,

Using an IStringLocalizer for localization is covered in this page in the documentation: https://docs.fluentvalidation.net/en/latest/localization.html#istringlocalizer please re-read that page first as it explains what you need to do. To summarise:

- Pass the IStringLocalizer instance _in to the validator's constructor_.
- You **_must_** use the lazily-loaded versions of WithName/WithMessage when using a localizer (ie pass in a Func, rather than the value directly) to ensure you get the results from the right language. The example in the documentation uses `WithMessage`, but the same applies to `WithName` too.

Both of these requirements appear to be missing from your example. 

This is what your validator should look like:

```csharp
public class CustomerValidator : AbstractValidator<Customer>
{
  // The localizer must be a constructor parameter. 
  public CustomerValidator(IStringLocalizer<Pages.Ressources.DefaultTranslations> localizer)
  {
   // You must use the lazy version of WithName, that takes a Func. 
    RuleFor(x => x.Forename).NotEmpty().WithName(x => localizer["Forename"]);
  }
}
```

I don't know what the "`<FluentValidator />`" element is in your code, as that isn't something that's part of this library. I'm assuming it's something custom you've written? If so, you'll need to ensure that it passes the localizer through to the validator's constructor (as above).
