### ISSUE TITLE
Architecture question: Is injecting repository into validator correct from architecture point of view?

### ISSUE THREAD

**Issue by dalibor-sanzeru** [FluentValidation/FluentValidation#1395]
This is architecture related question, but maybe it would be interesting to menton this on wiki page. 

Is injecting repository into FluentValidator corect from architectural point of view?

E.g. Validation of uniqness of newly registered username -> check in dataabase if user name was not used in past registrations.

Is injecting repository correct?

Thanks for answer.

**Comment by JeremySkinner** [comment]
Hi, the answer is "it depends". 

There's no such thing as a "right" or "wrong" architecture - this is entirely dependent on your specific application, and what makes sense for you. Design patterns, architecture guidance etc are all context-dependant and there are many factors involved. The size of the application, whether it's distributed, the experience of your team, the size of the team are all factors that should be considered when adopting a particular architecture or patterns etc. 

Because of this, it isn't sensible for me to make generalisations about architectural designs, and why this is not something I'll include in the documentation. It's up to you to evaluate and decide what makes sense to you. 

A better question to ask would be: "does this add value to your application and help you deliver what the client needs."
