### ISSUE TITLE
C# -- Argument 1: cannot convert from 'object' to 'FluentValidation.IValidationContext'

### ISSUE THREAD

**Issue by memo1093** [FluentValidation/FluentValidation#1446]
**Which version of FluentValidation are you using?**
version 9.0.1

**Which version of ASP.NET are you using?**
.Net Framework 6.4.1

**Describe the issue that you're having**
i am taking this error :
`Argument 1: cannot convert from 'object' to 'FluentValidation.IValidationContext'`

from this code for **entity**:
```
public class ValidatorTool
    {
        
        public static void FluentValidate(IValidator validator, object entity)
        {
            var result = validator.Validate(entity);
            if (result.Errors.Count > 0)
            {
                throw new ValidationException(result.Errors);
            }
        }
    }
```

**Comment by JeremySkinner** [comment]
This is because the non-generic overload of `Validate` that takes an `object` has been removed. This is covered in the upgrade guide here: https://docs.fluentvalidation.net/en/latest/upgrading-to-9.html#removal-of-non-generic-validate-overload

If you read the instructions in the section "Removal of non-generic Validate overload" you will see a code example that explains what you need to do instead. You will need to create a ValidationContext, and pass in your entity to this.

```csharp
public static void FluentValidate(IValidator validator, object entity)
{
    var context = new ValidationContext<object>(entity);
    var result = validator.Validate(context);
    if (result.Errors.Count > 0)
    {
        throw new ValidationException(result.Errors);
    }
}
```

Please read the upgrade guide to become familiar with the breaking changes in 9.0.

**Comment by memo1093** [comment]
Thanks so much. I tried just overload with IValidationContext like ` var result = validator.Validate((IValidationContext)entity);` and i got System.InvalidCastException error when i want to running command. 
Your code worked. Thanks !

**Comment by JeremySkinner** [comment]
Great, glad it works!
