### ISSUE TITLE
Support Collection length validation with LengthValidator

### ISSUE THREAD

**Issue by OldrichDlouhy** [FluentValidation/FluentValidation#1449]
The ASP.NET Core data annotation `MaxLengthAttribute` can be used both on strings and collections. The Fluent Validation `LengthValidator` and its children can be used only on strings.

As a result, to validate the length of collection, the following code, or some similar workaround, must be used:

``` CSharp
RuleFor(e => e.Collection.Count).LessThan(10);
```

While functional, it does not cope well with Swashbuckle integration (https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation) as the rule is not visible in the OpenAPI document:

``` JSON
...
"collectionWithMaxLengthAttribute": {
  "maxLength": 5,
  "type": "array",
},
"collectionWithFluentValidation": {
  "type": "array",
},
...
```

If `LengthValidator` will support ICollection, the rule could be simplified to 

``` CSharp
RuleFor(e => e.Collection).MaxLength(10)
```
and the "maxLength" will show in the OpenAPI document.

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion. Changing the `LengthValidator` to support this is not completely straightforward due to its translated error messages:

```
"'{PropertyName}' must be between {MinLength} and {MaxLength} characters. You entered {TotalLength} characters."
```

This message doesn't really make sense in the context of anything that isn't a string. Changing this (or adding a new message) and re-translating it into all the supported languages is a large undertaking, so you'll understand that this is generally something I'd try to avoid. 

Instead I'd suggest looking at using the `Transform` method to apply a transformation to the collection, rather than accessing the Count inside the rule definition:

```
RuleFor(x => x.Collection).Transform(col => col.Count).LessThan(10);
```

This keeps the rule defined on the collection property itself, but still allows you to use the Count for purposes of validation. I don't know anything about Swashbuckle, but would this work for you?

**Comment by OldrichDlouhy** [comment]
Thanks for quick response. 

As a quick workaround your proposal works, but the resulting OpenApi is still not correct (I understand that it is not responsibility nor fault of Fluent Validations).

My final solution was to create custom `PropertyValidator` class that allowed me to add it to the Fluent Validation to OpenAPI Swashbuckle mapping.

Anyway, I believe that having out of box rules for collection length may be useful for FluentValidations, though I leave it to your discretion if and when you will implement it. In other words, feel free to close this issue as you see fit.

Once again, thanks for the response.

**Comment by JeremySkinner** [comment]
Great, I'm glad you have a working solution, and that's precisely why FV is designed to be extensible :)
