### ISSUE TITLE
'Validate' extension methods may appear too similar

### ISSUE THREAD

**Issue by KindElk** [FluentValidation/FluentValidation#1467]
**Is your feature request related to a problem? Please describe.**
The `DefaultValidatorExtensions` has two `Validate` extension overloads, those are too similar in some cases.
`public static ValidationResult Validate<T>(this IValidator<T> validator, T instance, params string[] properties)` – for validation limited to list of properties and 
`public static ValidationResult Validate<T>(this IValidator<T> validator, T instance, IValidatorSelector selector = null, string ruleSet = null)` – for validation limited to set of rules limited with their rulesets and given `selector`.

_The issue_: call `validator.Validate(instance, "someString")` will validate property named "someString" and very similar `validator.Validate(instance, ruleSet: "someString")` will run whole "someString" ruleset. At some point formal parameter name `ruleSet` was missed and I was wondering why nothing is validated when I'm calling `validator.Validate(instance, "*")`.

**Describe the solution you'd like**
The simplest solution (to remove `params` from the first method signature) will be most convenient, but most probably will cause backward compatibility issues.
Another good option is to have new method(s) created with more explaining names, like `ValidateProperties` and/or `ValidateRestrictRules` marking old ones as `obsolete` at the same time with some defined EOL point.

**Describe alternatives you've considered**
Sure, any other options that'll help explicitly differentiate these two overloads without having them compatible are considerable.

**Comment by JeremySkinner** [comment]
Hi there, thanks for the suggestion. This is historical, as the overload that took a `params string[] properties` was in place before rulesets were added.

As this would be a breaking change it isn't something that would be considered outside of a major release. Version 9.0 was recently released, so we wouldn't be looking at a 10.0 release for probably another year, but can take this into consideration when it comes time to plan 10.0.

**Comment by JeremySkinner** [comment]
Hi @KindElk 

I had a think about this further today. I'm not too keen on adding new validation methods, but I have an alternative idea instead.

I'm not keen on adding new validation methods as it means we'll end up with a *lot* of new overloads, and I want to avoid complicating the API surface area. If we did this we'd have to add the following methods:
- ValidateProperties(params string[])
- ValidateProperties(params expression[]) 
- ValidatePropertiesAsync(params string[])
- ValidatePropertiesAsync(params expression[])
- ValidateRuleset(params string[])
- ValidateRulesetAsync(params string[])
- ValidatePropertiesAndThrow(params string[])
- ValidatePropertiesAndThrow(params expression[]) 
- ValidatePropertiesAndThrowAsync(params string[])
- ValidatePropertiesAndThrowAsync(params expression[])
- ValidateRulesetAndThrow(params string[])
- ValidateRulesetAndThrowAsync(params string[])

That's a lot of new overloads!

Instead of this, I'd suggest a method that allows you to pass in a strategy instance, something like `Validate(T instance, IValidationStrategy strategy)` 

The strategy would allow you to use any combination of ruleset/properties/selector/throwing:

```csharp
// Include explicit properties
validator.Validate(model, options => {
  options.IncludeProperties("Foo", "Bar");
  // Or
  options.IncludeProperties(x => x.Foo, x => x.Bar);
});

// Include explicit rulesets
validator.Validate(model, options => {
  options.IncludeRuleSets("ruleSet1", "ruleSet2", "default");
});


// Combinations
validator.Validate(model, options => {
  options.IncludeRuleSets("ruleSet1", "ruleSet2");
  options.ThrowOnFailure = true;
});
```

(and there would be an async overload). 

This avoids creating a lot of new method overloads, is consistent with the "fluent" nature of the library and allows you to be more explicit about what's included. It also would allow more customization of how these features work. The existing implementations are in extension methods, which can't be overridden, while these options would be part of AbstractValidator, and can be customized by overriding Validate/ValidateAsync. 

Would that work for you?

**Comment by JeremySkinner** [comment]
FluentValidation 9.1 is now available on nuget with this change.
