### ISSUE TITLE
Support for validation rule metadata

### ISSUE THREAD

**Issue by anaximander23** [FluentValidation/FluentValidation#1468]
I'm writing an API that powers a webapp with dynamic form generation, and as part of that, we're generating fairly detailed metadata to describe the data. As part of this metadata, we're adding descriptions of the validation rules that will be applied to the data. This can be used to allow a client app to select matching rules for client-side validation, or simply as integration hints to API consumers.

Below is a sample of some validation rule metadata:

```
"validation": [
    {
        "rule": "IsRequired",
        "message": "This field is required"
    },
    {
        "rule": "MinimumLength",
        "message": "Name cannot be less than 5 characters"
        "value": 5,
    }, 
    {
        "rule": "MaximumLength",
        "message": "Name cannot be more than 50 characters",
        "value": 50
    }
]
```
*(The above is only a rough example for illustrative purposes.)*

The issue I'm facing is that it's not straightforward to gather all of the information needed to build this metadata. Currently, I'm using the registered `ValidatorFactory` to get a validator for the relevant type, and creating an `IValidatorDescriptor` from it. From there, I use `.GetMembersWithValidators()` and iterate through that collection, passing each rule to a factory of my own devising that produces an inspector based on the validator type, which is then able to extract the relevant data and return it.

This is a little clunky, and there's still no way to access certain information. For example, it's not easy to get hold of the error message template, because the message may be constructed on the fly in various ways, and doing so requires passing in a validation context, which doesn't exist at this point.

Would it be possible to add built-in support for producing a simple description of a rule? I'm making some progress with my inspector-factory approach, but I feel that a built-in method would be more straightforward.

**Comment by JeremySkinner** [comment]
Hi there, thanks for the suggestion.

Using the ValidatorDescriptor is the way to go to achieve this, but you're right that this isn't ideal. There is always a tradeoff between functionality and metadata. The more complex the functionality and behaviour, the harder it is to produce easily consumable metadata. 

>  For example, it's not easy to get hold of the error message template, because the message may be constructed on the fly in various ways

Yes that is definitely the big one. I'd suggest you take a look at what we do in the ASP.NET integration, which has to do something similar in order to do client-side message generation. Essentially, we check if the user is using a built-in error message, or a custom one. If they're using a built-in one, then certain placeholders are not accessible except at runtime, so can't be exposed easily as metadata, and as such we strip them out and use a "simplified" version of the message instead. [Here's an example for how we generate the clientside message for the length validator.](https://github.com/FluentValidation/FluentValidation/blob/master/src/FluentValidation.AspNetCore/Adapters/StringLengthClientValidator.cs)

**Comment by anaximander23** [comment]
Thanks for the tip; I'll have a look at the ASP.NET Core example. It sounds like a good approach - as this is for metadata in a fairly consumer-agnostic setting, it's quite alright to leave the message in a simplified or templated form for the consumer to work out how to handle; they're under no obligation to use it as-is (or at all).

I am developing a framework for dynamically building API metadata as part of the application suite I'm currently working on, but it's not just for the validation side. It includes all sorts of info regarding property types, default values, labels, etc. so I'd have to look at extracting the FV-relevant parts into a neat-ish package. However, as there's no proprietary aspects or internal business logic in this code, I have tentative approval from my manager at work to open-source it (assuming there's no objections from higher up, or the legal team), so I'd definitely be happy to contribute it if it's something you'd be interested in having.

As for the maintenance headache, you're probably right, and for that reason (and also because of the sheer flexibility of FV in adding your own cusotm logic) I would always be looking to keep it pretty lightweight, and focus mostly on being a framework that lets a developer define how their validation rules should look in the metadata, rather than being a magic black box that does it all for you. That said, I think a certain level of automatic behaviour shouldn't be too hard; getting hold of stuff like the comparison values for GreaterThan, LessThan, Between etc. only took a few lines of code, for example.

**Comment by jzabroski** [comment]
@anaximander23 Check out https://www.nuget.org/packages/MicroElements.Swashbuckle.FluentValidation/

**Comment by jzabroski** [comment]
@JeremySkinner It might be worth doing if the MicroElements.Swashbuckle.FluentValidation project would benefit as well.

@petriashev what do you think?

**Comment by petriashev** [comment]
I have some limits in getting validation metadata now.
1. MicroElements.Swashbuckle.FluentValidation generates OpenAPI schema before any validation occurs. 
2. OpenApi does not support runtime logic and conditions
3. I have to use some hacks to retrieve validation metadata from Includes for example

If FV will implement more validation metadata I will use it of cause! )

**Comment by jzabroski** [comment]
After thinking about this, it would be handy for FluentValidation to support a sort of Mirrors API that reflects basic information, and then we can write generic tests like, "For entity T, all decimal properties should have a ScalePrecisionValidator."  Maybe this is possible today and I am just being lazy and not realizing it.

**Comment by jzabroski** [comment]
One more thought, @JeremySkinner .  If we went down the route of a Mirrors API, some Mirror requests could reflect back BrokenMirrorResult to the API consumer, indicating that the expression needs human intervention to create metadata that is understandable by humans.

**Comment by JeremySkinner** [comment]
@jzabroski This isn't something I'm personally planning on working on, and I'd consider it largely out of scope for the project. But if it's something you're interested in and want to build, then I'd suggest building it as a separate package. 

As an aside, I notice that you open a lot of feature requests in this repo, and I am simply not able to keep up with everything you want, especially as the majority of it is extremely niche and complex. 

If these are things you're passionate about and consider valuable, then why not have a go at writing them yourself? If you chose to do this then I'd be willing to provide you with guidance where necessary/appropriate, but you'd need to take responsibility for developing and maintaining it. Constantly asking me to build new features for you is not feasible - as I've explained to you before, this is something I do for free in my spare time and do not have the capacity to take up every feature request you. Thanks for understanding.

**Comment by jzabroski** [comment]
@JeremySkinner  Hi, thanks for your thoughtful reply.  I'm a bit embarrassed I'm such a passionate user of your repository that I'm one of the top contributor of comments but have thus far not really contributed any code.  I was mainly trying to contribute some thoughts on how this library could be made even more useful.  Some of these thoughts are perhaps deep and insular, and it is difficult to brainstorm and simultaneously not overwhelm the intended audience.  It's an art form and one I try to cultivate with years of experience, but still need more growth.

As for collaborating, I think that is reasonable.  However, I'm not asking for you to build new features for me.  I'm just trying to help brainstorm how to make the project even better.  Some of these past attempts were misguided because I simply didn't know the full breadth and scale of what is possible.  In terms of time, I have invested a lot of time the last two years in RazorLight and FluentMigrator and have effectively taken over both of those repositories.  I darted into those because my general sense is you have this project under control and a strong vision and command, whereas I use those two projects as well and I sensed they could use some more TLC.

In terms of the Mirrors idea, it was based on some recent PRs I saw you make around expression tree handling.  I thought it might actually give you some ideas worth thinking about, not annoy you.

Cheers.
