### ISSUE TITLE
Cannot Mock<IValidator<Entity>> and ThrowException

### ISSUE THREAD

**Issue by m4ss1m0g** [FluentValidation/FluentValidation#1485]
**Which version of FluentValidation are you using?**
9.1.1

**Describe the issue that you're having**
On previous version I can Mock<IValidator<T>> setup Validate returning ValidationResult with List<ValidationFailure> and test for throwing ValidationError

```
var validator = new Mock<IValidator<Entity>>();
validator.SetupFail();

// Validator is passed to another class that call 
// validator.Validate(instance, options => options.ThrowOnFailures());

await Assert.ThrowsAsync<ValidationException>(() => handler.Handle(request, validator.object));

// Extension method

public static ValidationResult FailResult => new ValidationResult(new List<ValidationFailure>() { new ValidationFailure("Foo", "Bar") });

public static Mock<IValidator<T>> SetupFail<T>(this Mock<IValidator<T>> validator)
{
	
	validator.Setup(p => p.Validate(It.IsAny<T>())).Returns(FailResult).Verifiable();
	validator.Setup(p => p.ValidateAsync(It.IsAny<T>(), It.IsAny<CancellationToken>())).ReturnsAsync(FailResult);

	validator.Setup(p => p.Validate(It.IsAny<IValidationContext>())).Returns(FailResult).Verifiable();
	validator.Setup(p => p.ValidateAsync(It.IsAny<IValidationContext>(), It.IsAny<CancellationToken>())).ReturnsAsync(FailResult);
	
	return validator;
}
```
**Expected Behaviour**
Throw Exception

**Actual Behaviour**
No Exception is Throw

**Note**
I looked on source code and I found the code below on `AbstractValidator`; question: is still possible to mock IValidator for throwing exception when error ?

```
protected virtual void RaiseValidationException(ValidationContext<T> context, ValidationResult result) {
	throw new ValidationException(result.Errors);
}
```

A possible solution is to add to `IValidationContext` and set `public`
`internal bool ThrowOnFailures { get; set; }`

When setup mocking I can select to return errors or raise error.

**Comment by JeremySkinner** [comment]
Hi,

Responsibility for throwing the exception has been moved into the validator in `RaiseValidationException`, this is so that validator subclasses can override this method and customise the exception-throwing process (which they couldn't before). By mocking the vaidator , you're essentially bypassing all of its behaviour, so no, it's not possible to mock this.

I can look at exposing the getter of the `ValidationContext.ThrowOnFailures` property publicly. Your mock could then check this, and then throw the expected exception itself. Would that work for you if I made this change?

However, be aware that by doing this you're actually testing the *mock*, not the *validator*, which is essentially a pointless exercise, as the mock and the runtime validator could end up behaving differently. I would highly suggest *not* doing this, and instead treat the validators as black boxes. Don't mock them, but instead pass in input in a known valid or invalid state. This leads to much less brittle tests in the long run. However I'm also aware that it may not be possible to rewrite your tests in this way if you already have lots of them.

**Comment by m4ss1m0g** [comment]
@JeremySkinner First of all thanks for your quick response and for the fantastic library !

> However, be aware that by doing this you're actually testing the mock, not the validator, which is essentially a pointless exercise

I partially agree with your "vision", in some situation throwing exception by validator is a trigger for other code.

**Comment by JeremySkinner** [comment]
> in some situation throwing exception by validator is a trigger for other code.

Yes, which is why it's better to have a real validator instance which receives valid/invalid input to trigger a "real" exception. If you mock this, then you can end up in a situation where the mock throws an exception, but the real validator wouldn't (eg if the `RaiseValidationException` method was overridden, or some other change had been made). By mocking the validator you're assuming it'll behave in a particular way when given certain input, but that isn't necessarily the case, which leads to brittle tests.

**Comment by JeremySkinner** [comment]
I've pushed out 9.1.2, which makes the getter public on ValidationContext.

**Comment by m4ss1m0g** [comment]
> I've pushed out 9.1.2, which makes the getter public on ValidationContext.

Many thanks !
