### ISSUE TITLE
A clearer explanation of the .Transform.

### ISSUE THREAD

**Issue by SomeProgrammerGuy** [FluentValidation/FluentValidation#1515]
**Is your feature request related to a problem? Please describe.**

As too the documentation "you can use the Transform method to transform a property value prior to validation being performed against it." Noting "prior" which seems only within the context of  Fluent Validation. 

**Describe the solution you'd like**

Excuse me if I have missed something (I'm only using this in anger now) but I would like the ability to keep what I have "transformed". when "it" is passed from the validation. For example lets say I trim() a field using transform, it would be nice to still have that field trimmed when it has passed through Fluent Validation. For note I'm well aware of model binders etc etc, but I prefer not to mix up two different systems so to speak if I can help it. If I'm doing it through this library then it would be nice to do it all in one place. Maybe something like an additional .TransformAndKeep etc. I'm sure you get the idea.

I'm sure this isn't related but just to be thorough I'm doing **stuff** like this on a .NET Core 3.x API Controller: 

```
   FooApiModelValidator validator = new FooApiModelValidator();
   ValidationResult validationResult = validator.Validate(fooApiModel);
```

As I like the control it gives me this way rather than in Startup.cs.

I mostly avoid 3'rd party library's like the plague where it's sensible but this is one of the few I really like. It's just simple and works . Good Job...

:-)

**Comment by JeremySkinner** [comment]
Hi, a call to `Transform` is only applicable to the rule in which it's defined. This is by design - separate calls to `RuleFor` act independently, and do not affect one another. 

Additionally, FluentValidation never changes the model or sets the value of properties, so it won't write the transformed value back to the property. Again this is by intentional - FluentValidation is not intended to modify the object being validated in any way (or have any kind of side affects - it wouldn't be thread safe). It only ever reads values, never writes them back, and this isn't something that will be changed. 

If you need to do this kind of thing, it's much better to do it in a surrogate property in your model itself, which you can then access. Transform is intended for a one-shot kind of transformation that is only needed inside a single rule. If you need something more permanent, you should move the responsibility for this outside of FluentValidation (ie a surrogate property). Alternatively, you could override the `PreValidate` method and apply your transformation in there prior to the rules being executed, meaning they'd always be invoked against the transformed value so you wouldn't need a call to Transform. However I wouldn't personally recommend this - its better to treat the validators like pure functions that have an input and an output, and never have any side effects.

Hope that makes sense.

**Comment by SomeProgrammerGuy** [comment]
Thank you for the response. Yes that makes complete sense.

I've added a JsonConverter converter to my project and all is working fine.

:-)
