### ISSUE TITLE
IsValid should return true for ValidationResult without failures with Error severity

### ISSUE THREAD

**Issue by azsdaja** [FluentValidation/FluentValidation#1519]
If my validation yields no actual errors, but there is at least single ValidationFailure with Info or Warning severity, then IsValid returns _false_.

The behaviour expected by common sense is to get _true_ in such case.

**Comment by JeremySkinner** [comment]
Hello,

`IsValid` indicates the presence of at least one `ValidationFailure`. If a failure is generated, then the object is not valid. Validity and severity are not linked. 

The severity enum is just metadata - you can use it however you like when inspecting the results and act upon them accordingly, but the current behaviour is intentional and isn't something that will be changed.
