### ISSUE TITLE
FluentValidation adapter for EntityFramewok Core

### ISSUE THREAD

**Issue by weitzhandler** [FluentValidation/FluentValidation#1538]
**Is your feature request related to a problem? Please describe.**
Some Entity Framework Core's column settings can be inferred from registered FluentValidation settings, instead of having to define them twice. (like nullable columns, string length etc.).

**Describe the solution you'd like**
A library that reads FV's settings and applies them into EF Core's entity configuration.

Here's an example: [weitzhandler/FluentValidation.EntityFrameworkCore](https://github.com/weitzhandler/FluentValidation.EntityFrameworkCore)

Ideally, I'd PR an integration of that library into FV as a separate package. In this case I'll ensure the coding standards match.

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion. 

This would be out of scope for the main FluentValidation project, and would definitely better as a separate package. If it's something that you think would be useful for the community then you are very welcome to support and maintain this, but this would need to be maintained externally from the FluentValidation repo (as otherwise I have to commit to personally procde support for it, which is not something I'm able to do for something that's out of scope for for the project).

If you have any questions about working with FluentValidation's internal API, then I'd be very happy to answer these, but this isn't something that we can bring into the repository. 

Hope that makes sense

**Comment by weitzhandler** [comment]
Thank you so much!
I definitely understand your time limitation as you are already doing so much in this project, and yes I can manage it externally, though I did give you access to the repo just in case you have the urge to shut down something.

I do have a few questions regarding the NuGet package:

- Can I use the FV icon?
- Can I publish it under `FluentValidation.EntityFrameworkCore`?
- What version should I publish it at? Should I match the FV version or start from 0 or from the current version?

**Comment by weitzhandler** [comment]
> As an example, the Blazor integration is handled in the same way

I have a future desire to implement UWP integration too. But the EF one was a small effort and easy to implement so I started here.

**Comment by JeremySkinner** [comment]
Generally I'd suggest using your own icon to differentiate the packages (for example, one of the blazor integration packages used a modified version of the icon: https://www.nuget.org/packages/Accelist.FluentValidation.Blazor) 

> Can I publish it under FluentValidation.EntityFrameworkCore?

The generical convention is to publish the package under `<YourCompanyName>.FluentValidation.EntityFrameworkCore` (the FluentValidation.* packages are reserved for packages that are officially part of the core project).

 > What version should I publish it at? Should I match the FV version or start from 0 or from the current version?

I'd recommend you version this completely independently, so start at 0.x for your prerelease, and then 1.0 once you're stable etc. Then bump the major version for breaking changes.

**Comment by weitzhandler** [comment]
Thank you so much for your kind and detailed input!

**Comment by weitzhandler** [comment]
Package published [here](https://bit.ly/33NQVSY).
