### ISSUE TITLE
Automatic registration of Property Validators via DependencyInjectionExtensions

### ISSUE THREAD

**Issue by augustoproiete** [FluentValidation/FluentValidation#1572]
Property Validators are currently not registered when using the FluentValidator's dependency injection extensions (e.g. `.AddValidatorsFromAssemblyContaining(...)`) because the `AssemblyScanner` only registers types implementing `IValidator<>`.

Therefore, when using Property Validators that require dependencies to be injected (e.g. parent/child relationship), Property Validators need to be manually registered.

Example structure:

```csharp
public class CustomerValidator : AbstractValidator<Command>
{
    public CustomerValidator(CustomerReferenceValidator customerRefValidator)
    {
        RuleFor(c => c.CustomerReference)
            .SetValidator(customerRefValidator);
    }
}

public class CustomerReferenceValidator : AsyncValidatorBase
{
    public CustomerReferenceValidator(SomeDependency dependency)
        : base("'{PropertyValue}' is not valid for '{PropertyName}'.")
    {
        // ...
    }
}
```

---

I propose `AssemblyScanner` to be updated to also register register types implementing `IPropertyValidator`, in addition to registering types implementing `IValidator<>`.

_Happy to send a PR as needed_.

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion, but this isn’t something that we’ll do. 

PropertyValidator must be instantiated uniquely each time they are used. They are stateful and hold information that is unique per rule. 

Having these globally injectable runs the high risk that that the a property validator instance I’ll be incorrectly shared. For example, if you need to use the property validator in 2 different rules, you *must* use 2 unique property validator instances - injecting and reusing the same instance will not work correctly. 

For example:

```csharp

public class CustomerValidator : AbstractValidator<Command>
{
    public CustomerValidator(CustomerReferenceValidator customerRefValidator)
    {
        RuleFor(c => c.CustomerReference)
            .SetValidator(customerRefValidator)
             .WithMessage("foo");

        RuleFor(c => c.OrherProperty)
            .SetValidator(customerRefValidator)
            .WithMessage("bar");

    }
}

```

In this example both rules would end up incorrectly with the message “bar”, because both calls to WithMessage modify the same PropertyValidator instance. 

This would be incredibly dangerous to enable by default. 

Instead you should inject the SomeDependency into the parent validator, instantiate 2 property validator instances and pass the dependency to each of them.  

Also as a side note, we will very likely be moving away from recommending PropertyValidators for custom validator going forward, in favour of the Custom method.

**Comment by augustoproiete** [comment]
> PropertyValidator must be instantiated uniquely each time they are used. They are stateful and hold information that is unique per rule.

Got it. This changes everything.

Thanks for the advice! I'm moving dependencies up the chain in the short-term, and will start to get acquainted with custom validators then.
