### ISSUE TITLE
CascadeMode.StopOnFirstFailure - re-add under different name?

### ISSUE THREAD

**Issue by dave-allen-cko** [FluentValidation/FluentValidation#1576]
**Is your feature request related to a problem? Please describe.**
We were using `CascadeMode.StopOnFirstFailure` in a many of our projects (at global and sometimes validator level), but this has now been deprecated. We have ways to reproduce the old behavior, but finding it a little verbose using the new CascadeMode options.

**Describe the solution you'd like**
Could this CascadeMode be brought back under a different name, e.g. `CascadeMode.StopOnFirstFailurePerRule` (for use at the global or validator level)?

**Describe alternatives you've considered**
To reproduce the old behavior, we use a combination of `CascadeMode.Continue` at the global level, and `CascadeMode.Stop` on each rule. This can be a little verbose though. If there's a simpler approach that we're missing, please let me know!

**Comment by JeremySkinner** [comment]
You can continue to use StopOnFirstFailure at the global/validator level - it isn’t being removed. It will generate a warning because the behaviour is unclear and confusing, but if you’re happy with this you can choose to suppress the warning.  

Please also see the discussion in https://github.com/FluentValidation/FluentValidation/issues/1558
