### ISSUE TITLE
OverridePropertyName does not determine display attribute of new property

### ISSUE THREAD

**Issue by cplankl** [FluentValidation/FluentValidation#1635]
Hello, 

currently I'm using FluentValidation 8.6.2 but the behavior is the same with version 9.5 in an Asp.Net MVC 5 and .Net 4.8 application.
We use DisplayAttributes for localizations. 
I have the scenario that I use a generic wrapper class `Wrapper<T>` in a view model `ViewModel` and this wrapper class is decorated with a display attribute. I use this wrapper in different view models with different display attributes. In my use case I want to validate the Value property in this generic wrapper class. It can be seen in the `ViewModelValidator ` class. For ordinary properties like the Caption property FluentValidation uses the DisplayAttribute to localize the PropertyName. But in my use case the DisplayAttribute for Description in the ViewModel cannot be found even if I override the property name with the extension method and the ValidationResult contains the string "... Description ..." instead of different "... DifferentDescription..." as I would have expected it by using the OverridePropertyName in the Validator.

Is there a way to get the display attribute value of the view model when I use a generic wrapper and validate one property in this property?

This is the full example:
```
class Program
{
	static void Main(string[] args)
	{
		ValidatorOptions.Global.DisplayNameResolver = (_, memberInfo, _) => memberInfo.GetCustomAttribute<DisplayAttribute>()?.GetName();
		
		var viewModel = new ViewModel();
		var validator = new ViewModelValidator();

		var result = string.Join(';', validator.Validate(viewModel).Errors.Select(x => x.ErrorMessage));
                // actual result is 'DifferentCaption' must not be empty.;'Description' must not be empty.
                // expected result would be 'DifferentCaption' must not be empty.;'DifferentDescription' must not be empty.
	}
}

public class Wrapper<T>
{
	public T Value { get; set; }
}

public class ViewModel
{
	[Display(Name = "DifferentCaption")]
	public string Caption { get; set; }

	[Display(Name = "DifferentDescription")]
	public Wrapper<string> Description { get; } = new();
}

public class ViewModelValidator : AbstractValidator<ViewModel>
{
	public ViewModelValidator()
	{
		RuleFor(x => x.Caption).NotEmpty();
		RuleFor(x => x.Description.Value).NotEmpty().OverridePropertyName(x => x.Description);
	}
}
```

**Comment by JeremySkinner** [comment]
Hi there,

From the code that you've posted, everything appears to be working as expected. I think you might have a couple of misconceptions about what's going on.

FluentValidation has 2 property names: 
- The display name. This is the version property name that is displayed inside the message (eg "Caption must not be empty"). This is set by using `WithName`.
- The raw property name. This is the name of the property with which the error message is associated in the ValidationFailure object. This is set by calling `OverridePropertyName`. 

If you don't specify a display name, then FluentValidation will fall back and use the raw property name. 

Neither of these make use of the `DisplayAttribute` by default.

You can set the `DisplayNameResolver` (as you have done) to look for the `DisplayAttribute`, this affects the display name (ie the version of the name that appears inside the error message - the equivalent of `WithName`). 

Calling `OverridePropertyName` changes the raw/underlying property name. It doesn't pass through the display name resolver (which is intentional) and isn't what you should be using here. 

What you basically need is a version of `WithName` which takes an expression, and passes it to the `DisplayNameResolver`. This doesn't exist out of the box, but you can write one for use in your application:

```csharp
public static class MyExtensions {
	public static IRuleBuilderOptions<T, TProperty> WithLocalizedName<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, Expression<Func<T, object>> otherProperty) {
		// Parse the expression tree.
		Expression expr = otherProperty.Body;
		if (expr is UnaryExpression u) {
			expr = u.Operand;
		}

		// If we found an member expression we can pass this to the DisplayName resolver.
		if (expr is MemberExpression m) {
			return rule.Configure(config => {
				config.SetDisplayName(context => {
					return ValidatorOptions.Global.DisplayNameResolver(typeof(TProperty), m.Member, otherProperty);
				});
			});
		}

		return rule;
	}
}
```

This creates a new method called `WithLocalizedName` which allows you to provide an expression, and passes it through the DisplayNameResolver.  You'd then use it like this:

```csharp
RuleFor(x => x.Description.Value).NotEmpty().WithLocalizedName(x => x.Description);
```

(note that you can't call it WithName as we already have an overload that takes a callback, which will conflict iwth the method signature) 

Also please be aware that with the upcoming 10.0 release, the `IRuleBuilder*` interfaces are likely to change so that they have an additional generic parameter, so you'll need to revisit this slightly if/when you upgrade to 10.0

Hope that helps

**Comment by cplankl** [comment]
Hi Jeremy,

Thank you very much for your solution. That's exactly what I need for my use case!
