### ISSUE TITLE
Testing - Integration or Unit or Both?

### ISSUE THREAD

**Issue by ChubbyArse** [FluentValidation/FluentValidation#1654]
Apologies for the vague question, but I'm wondering if we are testing our validation correctly. Currently, we are building models and integration testing via the API, but I'm not sure this is the best place to do it - it bloats the integration tests considerably.

The alternative is to unit test against the Validators explicitly - which is my preference. But what do I say when someone says you are aren't testing that the API calls are validated. Someone could turn off the validation in startup.cs and the integration tests and unit tests would still pass, but the integration of the two isn't.

I suppose that I could have a simple test per API that checks that a rudimentary validation check still occurs...

I'm really interested in what everyone else does.

**Comment by JeremySkinner** [comment]
My answer is going to be equally vague I’m afraid! Both approaches are valid but this is very context dependent - do what makes the most sense in your application given your constraints on time, budget and what you feel is necessary for your team. 

Also just a reminder that this is an issue tracker, not a discussion forum, so if you’re looking for lots of responses you may want to consider posting elsewhere as this is a general software design question rather than anything specific to FluentValidation. The only person likely to answer here is me 😊

**Comment by ChubbyArse** [comment]
Apologies Jeremy, I thought of posting elsewhere but was sure where.
