### ISSUE TITLE
validate only first or some items of list of objects, break foreach on certain condition

### ISSUE THREAD

**Issue by abdulrahmannady** [FluentValidation/FluentValidation#1662]
**Which version of FluentValidation are you using?**
FluentValidation.AspNetCore

**Which version of ASP.NET are you using?**
.NetCore 5

**Describe the issue that you're having**
Case: I want to validate only first item of list of objects, break foreach on certain condition

for Example 
classes
![classes](https://user-images.githubusercontent.com/77383973/109868873-dcf29980-7c70-11eb-8624-60c8d3381d8f.png)
and for validators
![validators](https://user-images.githubusercontent.com/77383973/109868892-e419a780-7c70-11eb-9cb0-8609196b22c0.png)

unexpected result appears at ModelState
![unexpected result](https://user-images.githubusercontent.com/77383973/109869093-20e59e80-7c71-11eb-9735-a899d5c218b6.png)

when changing to 
![change to RuleForEach](https://user-images.githubusercontent.com/77383973/109869167-34910500-7c71-11eb-9eef-4db7ef0cf6e2.png)

the required result appears
![right result](https://user-images.githubusercontent.com/77383973/109869265-538f9700-7c71-11eb-9659-3b3a3617220c.png)

but as you can see I want this result to apply only for first element or some elemnts then breakout
also can't use break here 
![Screenshot_3](https://user-images.githubusercontent.com/77383973/109869367-6efaa200-7c71-11eb-9dfc-d801ff1bc438.png)

**Comment by JeremySkinner** [comment]
Firstly, make sure that you have Implicit Validaiton turned *off* (this is the default, but just check you haven't enabled it in your application startup: https://docs.fluentvalidation.net/en/latest/aspnet.html#implicit-vs-explicit-child-property-validation - `ImplicitlyValidateChildProperties ` needs to be set to `false` or not set) otherwise ASP.NET will automatically validate each item in the collection regardless of what you set. 

> also can't use break here

That's correct, because it's not a `foreach` loop, but rather a declarative instruction that will be performed for each element in the collection. You can't "break" like this, as it isn't a loop. 

Beyond this, you haven't provided enough information to troubleshoot the issue further. Screenshots of code aren't enough to go on - you'll need to provide a small sample project that reproduces the issue.
