### ISSUE TITLE
Unable to use GreaterThan/LessThan validators with Nullable types

### ISSUE THREAD

**Issue by TheNybbler** [FluentValidation/FluentValidation#1681]
I have a uint? ArrayLength property that I'm trying to write a validator for.
If I try to use the following:
`RuleFor(x => x.ArrayLength).GreaterThan(0);`

Visual Studio give the error: The type 'uint?' must be a non-nullable value type in order to use it as parameter 'TProperty' in the generic type or method 'DefaultValidatorExtensions.GreaterThan<T, TProperty>(IRuleBuilder<T, TProperty>, Expression<Func<T, TProperty?>>)'

If I change the validator to this:
`RuleFor(x => x.ArrayLength.Value).GreaterThan(0).When(x => x.ArrayLength != null);`

If get a different error:
'IRuleBuilderInitial<CommandInterface, uint>' does not contain a definition for 'GreaterThan' and the best extension method overload 'DefaultValidatorExtensions.GreaterThan<CommandInterface, int>(IRuleBuilder<CommandInterface, int?>, int)' requires a receiver of type 'IRuleBuilder<CommandInterface, int?>'

It seems that int? values are supported, but uint? values are not.

**Comment by JeremySkinner** [comment]
Hi, the problem is you’re comparing a unit to an int (0). This won’t work as uint implements `IComparable<uint>` but not (`IComparable<int>`). The GreaterThan method makes use of IComparable so the types need to match up

Either change the call to GreaterThan to pass in a uint 0 rather than int 0 (I think you can just cast the 0) or switch the rule to do a `Must` check instead:

```
RuleFor(x=>x.ArrayLength).GreaterThan((uint)0);
//or
RuleFor(x=>x.ArrayLength).Must(val => val != null && val.Length > 0);
