### ISSUE TITLE
ParentContext is not accessible unless casting ValidationContext<T> to IValidationContext

### ISSUE THREAD

**Issue by MattJeanes** [FluentValidation/FluentValidation#1685]
### FluentValidation version

10.0.0

### ASP.NET version

.NET 5

### Summary

The example given in https://docs.fluentvalidation.net/en/latest/advanced.html#root-context-data does not seem to work. I have a possible workaround but I am not sure if it is appropriate or will even work.

Using the example in the link above results in:

![image](https://user-images.githubusercontent.com/2363642/113758087-5582c500-970b-11eb-848a-191008c29e54.png)

Exact error message: `error CS1061: 'ValidationContext<MyViewModel>' does not contain a definition for 'ParentContext' and no accessible extension method 'ParentContext' accepting a first argument of type 'ValidationContext<MyViewModel>' could be found (are you missing a using directive or an assembly reference?)`

Possible workaround(?)
```csharp
RuleFor(x => x.Surname).Custom((x, context) => {
    if ((context as IValidationContext).ParentContext.RootContextData.ContainsKey("MyCustomData"))
    {
        context.AddFailure("My error message");
    }
});
```
![image](https://user-images.githubusercontent.com/2363642/113758297-94b11600-970b-11eb-926d-a4759fbc20c4.png)

**Comment by JeremySkinner** [comment]
Hi, the example is wrong, you can just omit `ParentContext` and call `context.RootContextData`. I’ll update the example.

**Comment by MattJeanes** [comment]
Interesting, thanks! Our code uses ParentContext a lot for this purpose, so to be clear, the RootContextData regardless of how far down it is in the validation chain is always the same data and using ParentContext for this is unnecessary?

Should ParentContext be accessible at all in V10 now? It seems a little weird that ValidationContext<T> implements IValidationContext but we are unable to access it without casting, if that would even work.

I can't see anything on the V9 -> V10 upgrade guide about this unless I have missed it, perhaps a note there about this would be useful?

**Comment by JeremySkinner** [comment]
Yep, it’s the same instance used everywhere. It’s intended to be a way to share data that you can access anywhere in the validation process.

> Should ParentContext be accessible at all in V10 now?

No, you shouldn’t need to use it. In 9.x you had to use context.ParentContext as context is a `PropertyValidatorContext`, and ParentContext is a `ValidationContext<T>` but in 10.0 the  `ValidationContext<T>` Is passed in directly and we don’t use PropertyValidatorContext anymore. 

There’s a section in the upgrade guide that mentions that various places now take a ValidationContext instead of a PropertyValidatorContext, I’ll try and make it clearer that this also means you don’t need to access ParentContext anymore.

**Comment by MattJeanes** [comment]
That's perfect, thank you very much. I'll let you close the issue as you may want to keep it open to update docs etc, but that's my issue solved 😄

**Comment by JeremySkinner** [comment]
Thanks, I've updated the docs, they should publish momentarily.
