### ISSUE TITLE
I want to make faster for collection validation. How Can I do it. I am presently using RuleForEach but for 20k items its slow. taking 11 min to validate only 4 properites per item.

### ISSUE THREAD

**Issue by AryanVerma** [FluentValidation/FluentValidation#1692]
### FluentValidation version

FluentValidation.8.5.0

### ASP.NET version

4.7

### Summary

I want to make faster for collection validation. How Can I do it. I am presently using RuleForEach but for 20k items its slow. taking 11 min to validate only 4 properites per item.

 RuleForEach(a => a).Custom(ValidateSalesOrderName); length check
            RuleForEach(a => a).Custom(ValidateDesc); length check
            RuleForEach(a => a).Custom(ValidateSourceSystemId); length check
            RuleForEach(a => a).Custom(ValidateSourceSystemName); length check

### Steps to Reproduce

slow

**Comment by JeremySkinner** [comment]
Each time you call `RuleForEach` it'll iterate the collection again - try calling `RuleForEach` only once, and combining the contents of your custom methods rather than having multiple calls. 

Additionally, we have made major performance improvements to `RuleForEach` in FluentValidation 10.0, so you may want to consider upgrading.

Please note that FluentValidation 8.5 is an old version that is no longer supported, so we won't be making any updates to this version.
