### ISSUE TITLE
Add non-generic interface for EmptyValidator

### ISSUE THREAD

**Issue by wagich** [FluentValidation/FluentValidation#1697]
### Is your feature request related to a problem? Please describe.

I'm reading validator metadata to enhance a generated json schema. For the most part, this was easy to adapt to 10.x thanks to the provided non-generic interfaces that were introduced for the built-in client validation. Unfortunately, the `EmptyValidator` does not have such an interface and has to be identified by name.

### Describe the solution you'd like

Create the non-generic interface `IEmptyValidator` and implement it on `EmptyValidator<T,TProperty>`. 
It would be very nice if all the built-in validators could be identified using non-generic interfaces.

#### Before
```c#
IRuleComponent component;
switch (component.Validator)
{
    case INotEmptyValidator:
        // set json schema options
        break;
    default:
        switch (component.Validator.Name)
        {
            case "EmptyValidator":
                // set json schema options
                break;
            default:
                break;
        }
        break;
}
```
#### After
```c#
IRuleComponent component;
switch (component.Validator)
{
    case INotEmptyValidator:
        // set json schema options
        break;
    case IEmptyValidator:
        // set json schema options
        break;
}
```

**Comment by JeremySkinner** [comment]
Hi, using the `Name` property is the correct/recommended way to do this, rather than using the type. The non-generic interfaces are generally only in place where additional properties need to be exposed (for example, the Min/Max length on the length validators) as well as for backwards compatability where empty versions of these interfaces existed already.

That being said I'm happy to add it in this case as it's a trivial case, but I would recommend you use the Name to identify property validators going forward, as this is something that developers of property validators must provide.

**Comment by wagich** [comment]
@JeremySkinner Very good to know that `Name` is the recommended way to do this sort of thing - in that case, maybe it would indeed be better to not add even more legacy interfaces... 
For my use case it's just a (mostly accidental) convenience, so please feel free to close.
