### ISSUE TITLE
Custom Message from within MustAsync

### ISSUE THREAD

**Issue by LeahPike** [FluentValidation/FluentValidation#1701]
### FluentValidation version

9.2.2

### ASP.NET version

.NET Core 5.0.0

### Summary

Is it possible to provide the message within the MustNotContainNewScoresAsync so I can use values pulled from the database, giving a much more helpful message?

### Steps to Reproduce

``` C#
RuleFor(e => e.Scores).MustAsync(MustNotContainNewScoresAsync).WithMessage("New scores cannot be added").When(e => e.Id != 0);

private async Task<bool> MustNotContainNewScoresAsync(ModuleData scorecard, ICollection<Score> scores, CancellationToken cancellationToken)
   // custom logic
  // throw nice error message using values pulled from our database, used to validate the entry
   return true;
}
```

**Comment by JeremySkinner** [comment]
Hi, you'd need to use `CustomAsync` rather than `MustAsync` if you want to do that - it allows you to call `AddFailure` directly inside the callback where you can specify your own message - [see this page in the docs](https://docs.fluentvalidation.net/en/latest/custom-validators.html#writing-a-custom-validator) (the example uses Custom rather than CustomAsync but it's the same principle) 

(Also note that there have been some changes here between FluentValidation 9.x vs 10.x)

**Comment by LeahPike** [comment]
Perfect, thank you :)
