### ISSUE TITLE
Support internal types during assembly scanning via DependencyInjectionExtensions

### ISSUE THREAD

**Issue by iabdelkareem** [FluentValidation/FluentValidation#1741]
### Is your feature request related to a problem? Please describe.

Today FluentValidation.DependencyInjectionExtensions scan assemblies only for public types and ignore internals. 

In some projects where I wanted to encapsulate the implementations within the assembly, it became a blocker keeping me from using FluentValidation.DependencyInjectionExtensions because it only scans the public types. So I had to do custom assembly scanning or register the validators manually to the DI.

### Describe the solution you'd like

The solution is a simple change in the assembly scanner. I've created a PR with the change and a test that should solve the issue.

### Describe alternatives you've considered

1- Custom assembly scanning for validators
2- Manually register validators in the DI
3- Make validators public (Not preferred)

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion. 

Only including public types for assembly scanning is intentional - if a type is marked as internal this implicitly means it shouldn't be considered for use outside of its defining assembly, and including these within the auto-registration process would expose types to the container that the user may not have intended. 

I'm not totally against adding this, but it needs to be opt-in, with the default behaviour being not to include internal types.

**Comment by iabdelkareem** [comment]
Thank you for the quick response and explanation. I agree with you it's much better when including internal types is opt-in. I've updated the PR with the changes ^^

In my case is as you described, I'm having internal validators because I don't want them to be referenced outside the scope of its owning assembly. But I also would like the assembly scanning to discover them so that I can use them by referencing an abstraction (i.e., `IValidator<TypeToBeValidated>`) without having to register them manually.
