### ISSUE TITLE
Issue in Caching messages for multilingual application.

### ISSUE THREAD

**Issue by AditiG12** [FluentValidation/FluentValidation#1788]
### Is your feature request related to a problem? Please describe.

Currently we are working in multilingual application supporting 16 languages but here we are facing issues with validation messages.
Scenario1: If a user fires validation in English culture and then change the application culture to German and again fires validation than messages are shown in correct culture. Now suppose user, log out from the application and re-login, then again fire validations. This time user does not see the messages in the expected language, Instead the messages are shown last logged in language, which was German in our case.

### Describe the solution you'd like

Question 1: Are there any provision in the fluent Validations to support the multi-lingual messages?

Question 2: What will be the performance impact, if we do not fetch cached messages or simply if we remove caching in our application?

**Comment by JeremySkinner** [comment]
Hello,

Are you referring to FluentVaidation’s built-in messages or are you using some kind of custom localisation? 

If you’re talking about the built-in messages then FluentValidation always uses whichever locale has been set in `CultureInfo.CurrentUICulture;` when generating localised messages. The first thing you should check is that you’re setting `CultureInfo.CurrentUICulture;` correctly. 

If you’re using a custom localisation strategy then you should do something like this: https://docs.fluentvalidation.net/en/latest/localization.html#istringlocalizer

If this is not working as you expect please open this as a bug report, rather than as a feature request.

**Comment by AditiG12** [comment]
Hi 
Thanks for the quick reply. We are setting the current culture in the the thread. Also, for the messages we have written as below: 
  RuleFor(model => model.FirstName)
            .NotEmpty().WithMessage("Field cannot be empty"))
