### ISSUE TITLE
Fluent validation simple injector integration

### ISSUE THREAD

**Issue by sarabu07** [FluentValidation/FluentValidation#1829]
### FluentValidation version

8.6.2

### ASP.NET version

3.1

### Summary

https://github.com/simpleinjector/SimpleInjector/issues/926

The fluent validation don't allow integration with DI container other than Microsoft DI ?

### Steps to Reproduce

https://github.com/simpleinjector/SimpleInjector/issues/926

**Comment by JeremySkinner** [comment]
You can use FluentValidation itself with any DI container you like, just register validators with your container of choice and resolve them as required.  

However the automatic ASP.NET integration requires registering services with ASP.NET `IServiceProvider`. This is a requirement of ASP.NET, because it involves replacing parts of the ASP.NET pipeline, which can only be done with the IServiceProvider. Please review the FluentValidation documentation on working with ASP.NET https://docs.fluentvalidation.net/en/latest/aspnet.html

Please note for future reference that this issue tracker is for bugs in the FluentValidation library, it isn't a support forum, sorry.
