### ISSUE TITLE
Add notnull constraint

### ISSUE THREAD

**Issue by Toudahl** [FluentValidation/FluentValidation#1916]
### Is your feature request related to a problem? Please describe.

I made a change that broke our global error handling, and suddenly a lot of things where failing.

It turned out that the global error handling had been hiding incorrect usage of FluentValidation. This is of course our own problem and fault. But i feel a small change to the framework would have made it more clear.

Example of incorrect usage:
```
using FluentValidation;

var validator = new Validator();

var result = validator.Validate((Example?)null);

Console.WriteLine(result.IsValid);


class Validator : AbstractValidator<Example?>
{
    public Validator()
    {
        RuleFor(input => input)
            .NotNull()
            .WithMessage("dont.");
    }
}

class Example
{
    
}
```

We had incorrectly assumed that the NotNull method could be used to check the entire instance, not just individual properties

### Describe the solution you'd like

I would like the `AbstractValidator<T>` to be updated with the notnoll constraint. I am not intimately familiar with the framework, so perhaps other types should be updated too.

### Describe alternatives you've considered

I have not considered any alternative.

### Additional Context

For anyone treating all warnings as errors i believe this would be a breaking change. However, i think most people are not making the same mistake as we were.

**Comment by JeremySkinner** [comment]
Hi,

FluentValidation is intended to validate the properties of an object and this can't be done if the root object is null, so having a NotNull on the root instance doesn't really make sense as the entire validator can't even run properly if its passed a null reference. This is considered an invalid scenario and [we throw an exception if the root-level object is null](https://github.com/FluentValidation/FluentValidation/blob/044382a02a8ee209946ec16a62b8d44a4ad2b5e9/src/FluentValidation/AbstractValidator.cs#L406). Ideally you should ensure you don't pass a null reference to `Validate`, but you could also use `PreValidate` if you want to take some additional action if the root object is null - [this is covered in the docs here](https://docs.fluentvalidation.net/en/latest/advanced.html#prevalidate) 

Note that the above behaviour only applies to the *root* validator. Child validators simply won't be invoked if their corresponding property is null (and you should place the null check on the property itself at the parent level, rather than inside the child validator)
