### ISSUE TITLE
System.Text.Json is unable to deserialize FluentValidation.Results.ValidationResult

### ISSUE THREAD

**Issue by Arclight3** [FluentValidation/FluentValidation#1928]
### FluentValidation version

10.4.0

### ASP.NET version

6.0.202

### Summary

System.Text.Json is unable to deserialize FluentValidation.Results.ValidationResult, while Newtonsoft.Json is able to do it.

I filled an issue on dotnet runtime repo (https://github.com/dotnet/runtime/issues/68280) but they suggested to open one here because it might be that FluentValidation relies on conventions not supported by System.Text.Json or that it implements a converter only for Json.NET.

### Steps to Reproduce

Check this code in .NET 6:

```C#
var validationResult = new ValidationResult
{
    Errors = { new ValidationFailure("MyProperty", "Invalid MyProperty") }
};

// System.Text.Json
var serialized = JsonSerializer.Serialize(validationResult);
var deserialized = JsonSerializer.Deserialize<ValidationResult>(serialized);

// Newtonsoft.Json
var serialized2 = JsonConvert.SerializeObject(validationResult, Formatting.Indented);
var deserialized2 = JsonConvert.DeserializeObject<ValidationResult>(serialized2);
```

The deserialized variable contains a ValidationResult object with IsValid = true, and 0 Errors.
The deserialized2 variable contains a ValidationResult object with IsValid = false, and 1 Error.

The serialization operation produces an identical json string for both libraries, but the System.Text.Json fails to deserialize it back to a ValidationResult object.

**Comment by JeremySkinner** [comment]
I can't really see an issue here. We don't do anything special or provide a converter or anything like that. If it works with JSON.NET then I'd expect it to work with System.Text.Json too. I would've suggested that you report it to them, but I see you already did and they closed the issue 🤷  I'm not sure what conventions they'd be referring to. 

I'm not really able to help with this I'm afraid - it really needs someone who knows about System.Text.Json to investigate, which isn't something I have any experience with.

**Comment by crnd** [comment]
This is happening because of how deserialization is implemented in System.Text.Json as it currently doesn't support deserialization for collection properties without a setter (https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-6-0#add-to-collections-without-setters). The `Errors` property in `ValidationResult` is defined without a setter as `public List<ValidationFailure> Errors => _errors;`. The workarounds for this would be:
 * Define a setter
 * Define a custom converter
 * Use a public field

Having a setter or having a public field would both be changing the public interface so probably not worth it. If someone needs to be able to deserialize `ValidationResult`, they can always define a custom converter for it.

There is also some work going on with having support for deserializing to collection properties without setters but it has been postponed for three years now so wouldn't hold my breath: https://github.com/dotnet/runtime/issues/30258

**Comment by JeremySkinner** [comment]
@crnd thanks for the explanation, that makes sense. Yes it does seem that JSON.NET is fine deserializing without the public setter while STJ requires it. Exposing a setter isn't something we want to do for this property, so I think your suggestion of encouraging users to provide their own custom converter is the way to handle this.

**Comment by Vahdanian** [comment]
I noticed that the issue can be fixed by specifying a constructor as [JsonConstructor]. In fact every time "System.Text.Json" calls the default constructor in which the errors list will be initialized by an empty list and this will lead to failure in deserialization.
![Screenshot 2022-05-04 ](https://user-images.githubusercontent.com/46107508/166666419-7ab93fcc-be1b-4e19-9d10-ab4fa4f2310f.png)

Please also note that previous code in ValidationFailure.cs has rather the same issue and trying to deserialize an instance of this class will result in an exception.

![exception](https://user-images.githubusercontent.com/46107508/166666565-38f6ce9e-664a-4f6b-a224-df9fc1d50bc6.png)

**Comment by JeremySkinner** [comment]
That's vert frustrating. I'm really not keen on taking a dependency on STJ to work around their limitations.

**Comment by Vahdanian** [comment]
You are right. I'll close the pull request.

**Comment by JeremySkinner** [comment]
Ah I hadn’t seen that you’d opened a PR. I’ll take a look at it anyway. Although I’m not keen on taking a dependency on STJ it may be worth it if it is going to benefit a lot of users. I’ll review it when I get some spare time

**Comment by JeremySkinner** [comment]
I've had some time to think about this further and I think I've decided to opt for adding public setters to `ValidationResult` and a public parameterless constructor to `ValidationFailure`. This seems like the simplest option as it doesn't require adding an explicit reference to System.Text.Json (which I want to avoid), nor does it require end users to define their own type converters. 

The setter will preserve the same behaviour as the existing constructor (copies the list of failures and removes nulls). 

This will go into 11.0.2 which I'm aiming to release tomorrow.

**Comment by JeremySkinner** [comment]
If anyone has time, I'd appreciate a quick review of https://github.com/FluentValidation/FluentValidation/pull/1947

**Comment by JeremySkinner** [comment]
Published 11.0.2

**Comment by maxime-poulain** [comment]
Hello @JeremySkinner,

> Exposing a setter isn't something we want to do for this property,

I'd say that I am not a huge fan neither to change the modifier to that property to a public setter.

However, 
using the modifier as
```csharp
init
```

does work; see screenshot:

![image](https://user-images.githubusercontent.com/90202188/172684190-28474e92-6d51-40f6-a0cb-2b692e2e4b5e.png)

Only issue with this is that you need C# 9 +  to have that working.
So the use of a preprocessor is needed for the target frameworks netstandar 2.0/2.1 and netcore 3.1 which are still used by the library.

Dunno if you would consider having the property init therefore.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion but will keep it as a setter as changing it again would be a breaking change.
