### ISSUE TITLE
Null validators error message reports empty instead of null.

### ISSUE THREAD

**Issue by urielzen** [FluentValidation/FluentValidation#1976]
### FluentValidation version

11.1.2

### ASP.NET version

.NET 6

### Summary

The following rules:
```csharp
RuleFor(m => m.Prop1).Null();
RuleFor(m => m.Prop2).NotNull();
```
report the following errors:
```csharp
"NullValidator" => "'{PropertyName}' must be empty."
"NotNullValidator" => "'{PropertyName}' must not be empty."
```

### Steps to Reproduce

Probably not a bug, since in the docs is documented this way as well.
But I would like to know the reasoning behind this.

Why not return instead?:
```csharp
"NullValidator" => "'{PropertyName}' must be null."
"NotNullValidator" => "'{PropertyName}' must not be null."
```

I feel like this will make it clearer to the client what the backend is expecting. Because with the current error, for a string, the client could sent an empty string, technically fulfilling the error message, but still being unable to pass the validation until sending `null`.

**Comment by JeremySkinner** [comment]
This is intentional. Our default messages are intended to be end-user friendly and not include technical terms (or at least as end-user friendly as possible), so they can be directly displayed on web UIs etc. Hence the use of "empty" rather than "null".

You can override the messages if you want to use something else.
