### ISSUE TITLE
IRuleBuilderOptions to have generic property

### ISSUE THREAD

**Issue by kibernetik542** [FluentValidation/FluentValidation#1992]
### Is your feature request related to a problem? Please describe.

I have 2 identical extension method with difference int and int? ( depends on fields where I am using )

```
 public static IRuleBuilderOptions<T, int?> RangeWithWhen<T>(this IRuleBuilder<T, int?> ruleBuilder, string entity, int min, int max, Func<T, bool> expression) =>
 ruleBuilder.GreaterThanOrEqualTo(min).LessThanOrEqualTo(max).
WithMessage($"{entity} should be in range {min} - {max}").When(expression);


 public static IRuleBuilderOptions<T, int> RangeWithWhenNotNullable<T>(this IRuleBuilder<T, int> ruleBuilder, string entity, int min, int max, Func<T, bool> expression) => ruleBuilder.GreaterThanOrEqualTo(min).LessThanOrEqualTo(max)
.WithMessage($"{entity} should be in range {min} - {max}").When(expression);
```

### Describe the solution you'd like

Is it possible to use some generic ( something like where T : struct ), instead of int or int?,

I have several fields which is int, int?, decimal an decimal?, and when I want to create extension I have to create 4 seperate extension method.

Is it any way to use just one generic and use it everwhere?

### Describe alternatives you've considered

I wanted to achieve solution like one generic method, which is not accepting only exact type, and another solution maybe to use switch case and specify what it is ( int, decimal, double etc. ) and change result.

### Additional Context

`public static IRuleBuilderOptions<T, U> Id<T>(this IRuleBuilder<T, U> ruleBuilder, string entity) where U : struct => ruleBuilder.NotNull().NotEmpty().GreaterThan(0).WithMessage($"{ConstantsCollection.DefaultSpecify} valid {entity}");`

something like this

**Comment by JeremySkinner** [comment]
> Is it any way to use just one generic and use it everwhere?

Partially - You can reduce the number of overloads to 2 using generic constraints on `IComparable` - one for nullable types and one for non-nullable. You can't reduce it to a single overload as the C# compiler doesn't provide any way to convert between `T` and `Nullable<T>` for structs. 

```csharp
public static IRuleBuilderOptions<T, TProperty?> RangeWithWhen<T, TProperty>(this IRuleBuilder<T, TProperty?> ruleBuilder, string entity, TProperty min, TProperty max, Func<T, bool> expression)
	where TProperty : struct, IComparable<TProperty>, IComparable 
{
	return ruleBuilder.GreaterThanOrEqualTo(min).LessThanOrEqualTo(max)
		.WithMessage($"{entity} should be in range {min} - {max}").When(expression);
}


public static IRuleBuilderOptions<T, TProperty> RangeWithWhenNotNullable<T, TProperty>(this IRuleBuilder<T, TProperty> ruleBuilder, string entity, TProperty min, TProperty max, Func<T, bool> expression)
	where TProperty : IComparable<TProperty>, IComparable
{
	return ruleBuilder.GreaterThanOrEqualTo(min).LessThanOrEqualTo(max)
		.WithMessage($"{entity} should be in range {min} - {max}").When(expression);
}
```

You can also simplify your implementation using a single call to the range validator (`InclusiveBetween`) instead of calling both `GreaterThanOrEqualTo` and `LessThanOrEqualTo` as well: https://docs.fluentvalidation.net/en/latest/built-in-validators.html#inclusivebetween-validator 

For future reference please note that this issue tracker [is for bugs in the core FluentValidation library and isn't intended for general help/support](https://github.com/FluentValidation/FluentValidation/blob/main/.github/CONTRIBUTING.md#general-support-feedback-and-discussions).
