### ISSUE TITLE
Model Validation Errors not showing in ASP.Net Core 7.0 Html View

### ISSUE THREAD

**Issue by sahgilbert** [FluentValidation/FluentValidation#2025]
### FluentValidation version

11.2.2

### ASP.NET version

.Net 7.0

### Summary

- I have [followed the steps here](https://docs.fluentvalidation.net/en/latest/aspnet.html) to create an example project in Asp.Net Core 7.0.
- It all seems to work (invalid models are not successful when submitted to the controller).
- However, the validation errors do not show up in the Razor View.
- [Here is a sample project](https://github.com/sahgilbert/AspDotNetMVC7FluentValidationExample) which shows the problem of the errors not displaying in Html.

### Steps to Reproduce

[Use this sample project](https://github.com/sahgilbert/AspDotNetMVC7FluentValidationExample)

**Comment by JeremySkinner** [comment]
You have 2 main issues in your project.

Firstly, In your Create.cshtml, you've commented out the calls to `Html.ValidationMessageFor...`. You should uncomment these and the messages will show up. Alternatively if you want all the messages shown at the top of the page, then change `asp-validation-summary="ModelOnly"` to `asp-validation-summary="All"`. 

The second issue is the duplicate messages. This is happening because you've turned on both automatic validation, and manual validation, so validation is happening twice.

- Automatic validation is enabled by calling `AddFluentValidationAutoValidation` in your application startup
- Manual validation is enabled by injecting the validator into your controller and running the `ValidateAsync` method. 

You should do one of these *but not both*. This is covered in the documentation page that you linked to. 

Our recommendation (as per the documentation) is to only use validation, not automatic validation, so remove the call to `builder.Services.AddFluentValidationAutoValidation()` from your application startup. 

<img width="697" alt="image" src="https://user-images.githubusercontent.com/90130/201748653-1a638483-4398-4b0e-a551-b7042cd8170b.png">
