### ISSUE TITLE
Localize["validation messages without '{PropertyName}' hardcoded to the coding not language"]

### ISSUE THREAD

**Issue by MeaningOfLights** [FluentValidation/FluentValidation#2026]
### Is your feature request related to a problem? Please describe.

**BACKGROUND**
We're building a WebAPI that has Fluent Validations as well as our own custom validations. It's a major product upgrade targeted for an international market and every single label and text in the app will be proof read by translators.

Our PO files have typical custom validation messages, eg  'hours between 1 and 720' in French:
msgid "InitialLoadHours_Validation"
msgstr "Le nombre d'heures de données doit être compris entre 1 et 720."

**PROBLEM/ISSUE**
With Fluents' validation messages, for example Greater than in French:

"GreaterThanValidator" => "'{PropertyName}' doit être plus grand que '{ComparisonValue}'.",

This results in a validation message combined of English and French: **"'InitialLoadHours' doit être plus grand que 0."**

On the front-end the controls' label caption is 'Initial Load Hours' in English, in French though its rendered as 'Heures de charge initiales'. So it looks Micky Mouse having the controls name in English mixed in.

**PROPOSAL**
I'm wondering if its worth adding another style to your PO files, I'll start with a contribution covering a handful of languages, eg:

```
"EmailValidatorNoProp" => "Email address is not valid.",
"GreaterThanValidatorNoProp" => "Value must be greater than '{ComparisonValue}'.",
```

I'm not sure if the Property Names are even needed in the messages since us Dev's use the validationResult.PropertyName[0] to map validation messages to front-end controls:

```
{
    "data": null,
    "errors": [
        {
            "description": "'pingIntervalMins' must not be empty.",
            "field": "pingIntervalMins"
        }
    ],
    "isSuccess": false
}
```

**PITCH**
Unless there's a good reason to mix in the hardcoded Property Names causing mixed language messages (eg for backward compatibility), would you object if I made a second set of validation messages as proposed? 

### Describe the solution you'd like

The PO Files to have a second set of validation message without the Property Names embedded, eg:

```
"EmailValidatorNoProp" => "Email address is not valid.",
"GreaterThanValidatorNoProp" => "Value must be greater than '{ComparisonValue}'.",
```

### Describe alternatives you've considered

Stripping out the Property Name but then I'm left with a lowercase  "must be greater than", "must not be empty." While I can set the first char to be uppercase its safe to say that won't work across all languages. 

I thought about stripping the Property Names and prefixing the validation messages with Value or Input but again not all languages will start with a noun.

I thought about doing a look up of your messages to our own "Must be greater than" but I keep coming back to the source code:
https://github.com/FluentValidation/FluentValidation/blob/main/src/FluentValidation/Resources/Languages/EnglishLanguage.cs 

### Additional Context

Apologies if this has been raised before.

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion.

Our error messages are intended to be displayable directly to end-users, and referencing the property is useful for this purpose, particular in a 'validation summary' approach where you list all of the errors in a single place at the top of a pager (rather than inline next to the field, for example), so I think we do need to keep the property name placeholders in the messages. Supporting many different languages is already a large undertaking and this would be doubling the number of translatable strings - this isn't something I really want to support.

Note that the names embedded in the message using the `{PropertyName}` placeholder is the rule's *display name*, and the actual property name is only used if a display name hasn't been configured. 

The usual approach for handling this situation where you want to use the built-in messages but with is to set a translatable display name within your rule definition:

```csharp
RuleFor(x => x. InitialLoadHours).GreaterThan(0).WithName(x => localizer["Initial Load Hours"]);
``` 

FluentValidation's default behaviour is to use the property name if no display name is configured, but we'd generally recommend explicitly defining the display names by calling `WithName`, especially within a multilingual application.

You could also just replace the whole message entirely if you don't care about using FluentValidation's default messages by using a `WithMessage` callback instead.

An alternative approach could be to localize the display name globally by plugging into FluentValidation's language manager:

```csharp
// Create a custom language manager that adds your translated property names:
public class CustomLanguageManager : LanguageManager {
	public CustomLanguageManager() {
		AddTranslation("fr", "Member:InitialLoadHours", "Heures de charge initiales");
	}
}

// Enable the custom language manager in your application's startup routine
ValidatorOptions.Global.LanguageManager = new CustomLanguageManager();

// Set up a display name resolver in your application's startup routine to translate all properties. 
// All display names will be set based on this, rather than having to specify them using WithName.
ValidatorOptions.Global.DisplayNameResolver = (type, member, expression) => {
	if (member != null) {
		return ValidatorOptions.Global.LanguageManager.GetString("Member:" + member.Name);
	}

	return null;
};
```

If you don't want to provide translations for every property name then you could still implement your original suggestion by using a custom language manager and replacing FluentValidation's default messages with versions that don't contain the placeholder ([see the docs](https://docs.fluentvalidation.net/en/latest/localization.html#default-messages))

I hope one of these options gives you a way forward that works in your situation

**Comment by MeaningOfLights** [comment]
That's a perfect solution to get us by, I checked the thread about support and it's a major time drag[https://github.com/FluentValidation/FluentValidation/issues/1959]() .and I wonder if you can get any support from .Net Foundation? Anyway I'm happy with this workaround - many thanks for your countless late nights of coding!

**Comment by JeremySkinner** [comment]
Unfortunately that seems unlikely, the .net foundation has been a huge disappointment and doesn't really do much to help support its member projects, other than the CLA automation.
