### ISSUE TITLE
MemberNameValidatorSelector does not work with property path to child rule after version 11.1.1

### ISSUE THREAD

**Issue by abramchev** [FluentValidation/FluentValidation#2055]
### FluentValidation version

11.1.1

### Summary

I have old working code which uses MemberNameValidatorSelector to validate particular property path from the entity. In any version higher than 11.1.0 code stops working without any messages or exceptions. Error is not generate when expected.
Might be that MemberNameValidatorSelector utilization is not correct from the begging. It's taken from some samples time ago.

### Steps to Reproduce

Please, see working dotnetfiddle example [https://dotnetfiddle.net/5o03Fy](https://dotnetfiddle.net/5o03Fy)
Simply downgrade FluentValidation version to 11.1.0 to get correct results.
Thanks!
```
var validator = new RulesetChildValidatorRulesValidator();
var validatorSelector = new MemberNameValidatorSelector(new[] { "Orders.Quantity" });
var person = new Person
{
   Orders = new List<Order>
   {
      new() { Quantity = 0 }
   }
};
var fluentValidationContext =
     new ValidationContext<Person>(
     instanceToValidate: person,
     propertyChain: new PropertyChain(),
     validatorSelector: validatorSelector
);
ValidationResult result = await validator.ValidateAsync(fluentValidationContext);
//ERROR is Expected here

private class RulesetChildValidatorRulesValidator : AbstractValidator<Person> {
    public RulesetChildValidatorRulesValidator() {
        RuleFor(x => x.Surname).NotEmpty();
        RuleForEach(x => x.Orders).ChildRules(x => {
            x.RuleFor(y => y.Quantity).GreaterThan(0);
        });
    }
}
```

**Comment by JeremySkinner** [comment]
Hi,

`Orders.Quantity` isn't a valid property path - a property path takes indexers into account (eg `Orders[0].Quantity` is a property path, `Orders.Quantity` is not). The reason this worked prior to 11.1.1 is because of a of a bug in `ChildRules`, which always caused child rules to execute even when they weren't supposed to, which was fixed in #1982. 

The MemberName selector doesn't support what you want to do as there's no way to tell it to ignore indexers. You'd have to write a custom `IValidatorSelector` implementation to do what you want.

I do think this would be a useful feature to have though, so I'll investigate adding support for this in a future release. I'd imagine adding some kind of wildcard indexer support like `Orders[*].Quantity`, but I won't have availability to look into this for a while. If you're interested in putting together a pull request to add support for this then I'd happily review it, but otherwise I'd suggest writing a custom selector within your application.

**Comment by abramchev** [comment]
Hi Jeremy,
Unfortunately, I cannot get `Orders[0].Quantity` path working. It is exactly what I need. Final goal is to execute child rule for the given child entity, which comes from Blazor table OnFieldChanged event. From the sample above I'd have method receiving Order entity, but validator is defined for Person. Could you, please, point to any examples, if there are any?
And yes, for before issue 1982 validator was executed for all child entries and my code contains additional part to extract the single result.

**Comment by JeremySkinner** [comment]
> Unfortunately, I cannot get Orders[0].Quantity path working

That won’t work specifically for your case - it was just an example of a valid property path. The index changes for each item in the collection so you need some mechanism which is agnostic of the collection index. 

You’ll need to write a custom IValidatorSelector implementation that has specific handling for this rather than using the MemberNameValidatorSelector. I don’t have any examples for doing this I’m afraid, but take a look at the source code for MemberNameValidatorSelector and use this as the starting point. 

I will aim to get support for this into the library in the future but I don’t currently have availability to do this.

**Comment by abramchev** [comment]
I was able to fix current code by replacing 
```
var fluentValidationContext =
     new ValidationContext<Person>(
     instanceToValidate: person,
     propertyChain: new PropertyChain(),
     validatorSelector: validatorSelector
);
ValidationResult result = await validator.ValidateAsync(fluentValidationContext);
```
by
`ValidationResult result = await validator.ValidateAsync(person, v => v.IncludeProperties("Orders.Quantity"));`
Thank you for your support and effort!

**Comment by JeremySkinner** [comment]
@abramchev this code suffers from exactly the same problem.

Calling `IncludeProperties("Orders.Quantity")` still uses a MemberNameValidatorSelector under the covers and so will suffer from the same problem as `Orders.Quantity` is not a valid property path so will not solve your use case.

**Comment by abramchev** [comment]
Yes, you're right. I was again on old FV version by mistake.
