### ISSUE TITLE
Built-in unique rules

### ISSUE THREAD

**Issue by quilin** [FluentValidation/FluentValidation#2064]
### Is your feature request related to a problem? Please describe.

I have been using FluentValidation across four different projects for last couple of years, and has been enjoying it so far. However, I noticed that for every project we occasionally ran into requirement to validate list to contain unique features (usually the ids). The common solution to that is to go like this:

```cs
public MyValidator()
{
  RuleFor(r => r.Items).Must(r => r.Items.Select(i => i.Id).Distinct().Count() == r.Items.Count());
}
```
or with latest version of C# just `r.Items.DistinctBy(i => i.Id).Count()`.

Which is okay, of course, however it does seem to be quality of life feature to request.

### Describe the solution you'd like

The most simple solution seems to be adding the extension
```cs
public static IRuleBuilderOptions<T, ICollection<TItem>> UniqueBy<T, TItem, TKey>(
    this IRuleBuilder<T, ICollection<TItem>> ruleBuilder,
    Func<TItem, TKey> expression)
{
    return ruleBuilder.Must(prop => prop.DistinctBy(expression).Count() == prop.Count)
}
public static IRuleBuilderOptions<T, ICollection<TItem>> Unique<T, TItem>(
    this IRuleBuilder<T, ICollection<TItem>> ruleBuilder)
{
    return ruleBuilder.Must(prop => prop.Distinct().Count() == prop.Count());
}
```

### Describe alternatives you've considered

Using IEnumerable as constraint may be okay, but seems like you cannot count on that (you see what I did there? :D). Same goes for UniqueBy expression parameter, probably.

I also thought about the whole `ICollectionRuleBuilder<T, TCollectionItem>` to be able to add specific rules like `MaximumLength` or something like it. I'm not quite sure if that is an overengineering for such a scenario - I could not figure any additional rules that I needed for collections in my experience.

Of course, I also thought about "nevermind, just keep doing it like you do", but seems like there's plenty built-in rules that we have in FluentValidation for primitive types, and I would say that validating collection integrity is pretty common scenario.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion, but we're not currently planning on adding any more built-in rule types. FluentValidation is designed to be extensible so you can plug in your own rule types (as you are doing with extension methods) without them needing to be in the core library. 

Built-in rule types have a much higher maintenance burden (code, tests, translations across all our supported languages, docs) so we avoid adding new ones at this point unless it's not possible to do with existing extensibility points.

If you feel these would be useful to the community at large then please feel free to release them as a standalone package if you're willing to support them, otherwise I'd suggest keeping them as extension methods within your own projects.
