### ISSUE TITLE
'DefaultClassLevelCascadeMode' or 'DefaultRuleLevelCascadeMode' does not have the same effect as 'CascadeMode'

### ISSUE THREAD

**Issue by Michael-Swordys** [FluentValidation/FluentValidation#2081]
### FluentValidation version

11.4.0

### ASP.NET version

Asp.Net 6

### Summary

I'm using the CascadeMode setting which has the desired return, showing only the first error to be thrown.
![image](https://user-images.githubusercontent.com/80980887/222219454-b8e454ae-6866-4381-a13b-ecef76025615.png)

But this method has the warning of being obsolete, so I went to the documentation and saw that everything is already explained how it should be done!

I'm using this!
![image](https://user-images.githubusercontent.com/80980887/222219945-4ddf288f-38a0-4ec1-a210-635fc73f02ab.png)

but if i put it like in the documentation

![image](https://user-images.githubusercontent.com/80980887/222224150-2679f20d-9f2e-4335-b992-28bf96ba5f57.png)

![image](https://user-images.githubusercontent.com/80980887/222224234-1b86f323-7775-488f-b2e6-bb58a0dab37a.png)

unfortunately i will have the first error with blank and unwanted property

![image](https://user-images.githubusercontent.com/80980887/222224385-5304c216-75d1-40fd-8a09-697c4c897209.png)

note: my project is configured only to show the first two errors
![image](https://user-images.githubusercontent.com/80980887/222224735-7f0068b5-552b-49d9-b989-11ccf81f3afa.png)

### Steps to Reproduce

.

**Comment by JeremySkinner** [comment]
Hi. The documentation is correct - setting `ValidatorOptions.Global.DefaultClassLevelCascadeMode` to `Stop` behaves exactly the same as setting the deprecated `ValidatorOptions.Global.CascadeMode` to `Stop`. The behaviour is exactly the same between the 2.

The issue you're seeing is unlikely to be related to FluentValidation - the message you're seeing ("The input was not valid") isn't a message from FluentValidation - this is one of ASP.NET's own built-in messages that's generated due to some kind of data conversion issue. 

I'd suggest you check that the data you're sending to your endpoint can be converted to the target type. I'd also suggest you remove FluentValidation temporarily while you debug, that way you can be sure that FluentValidation is not the cause of your issue.

I can't help you any further than this as you've not provided a sample project to reproduce the issue.
