### ISSUE TITLE
How to test validator inclusion with FluentValidation >9.0.0?

### ISSUE THREAD

**Issue by rklec** [FluentValidation/FluentValidation#2087]
### FluentValidation version

9.0.0 (AFAIK) the first version that broke the code)

### Summary

I tried using the code from https://github.com/FluentValidation/FluentValidation/issues/1299#issuecomment-578743437 using FluentValidation 9.0.0 by @JeremySkinner. The question was asked by @CasperWSchmidt.

### Steps to Reproduce

```csharp
    public static void ShouldHaveIncludeRule<T>(this AbstractValidator<T> validator, Type includedValidator)
    {
        var includedValidatorTypes = validator.OfType<IncludeRule>()
            .SelectMany(rule =>
                rule.Validators.OfType<ChildValidatorAdaptor<T, T>>().Select(x => x.ValidatorType)
            );

        if (!includedValidatorTypes.Contains(includedValidator))
            throw new ValidationTestException($"Validator {includedValidator.Name} is not included");
    }
```

However [`IncludeRule`](https://github.com/FluentValidation/FluentValidation/blob/main/src/FluentValidation/Internal/IncludeRule.cs) does not seem to be exposed anymore, as such it cannot find/import this type anymore and the whole thing does not compile:
![grafik](https://user-images.githubusercontent.com/71322635/223744091-31a98628-1130-4833-9225-08857568b7fb.png)

Is there a way to fix this or expose `IncludeRule` again, so we can test for this again?
Or - I know it has been declined before to do it this way and I agree it has certainly disadvantages, but in some use cases the assessment of other alternatives (when you have a lot of tests/properties and don't want to copy them), so an alternative would be to add such a method to FluentValidation itself - maybe with a disclaimer that it is not the best way/should ideally not be used.

**Comment by JeremySkinner** [comment]
This isn't a good approach to testing validators, you should treat them as black boxes: supply them with input and assert on the results. Don't test the internal implementation details of how the validatir is built - this will lead to brittle tests. 

As I mentioned in the issue you linked to, you should think of `Include` as copying the rules from the child validator into the parent validator. They act as first-class rules inside this validator, so should be tested as if they had been defined directly inside the validator.

If you *really* want to do this, you'll need to update the code to use the newer API structure:

```csharp
public static void ShouldHaveIncludeRule<T>(this AbstractValidator<T> validator, Type includedValidator) {

	bool SearchForIncludedValidator() {
		foreach (var rule in validator) {
			if (rule is FluentValidation.Internal.IIncludeRule) {
				foreach (var component in rule.Components) {
					if (component.Validator is ChildValidatorAdaptor<T, T> c) {
						if (c.ValidatorType == includedValidator) {
							return true;
						}
					}
				}
			}
		}

		return false;
	}

	if (!SearchForIncludedValidator()) {
		throw new ValidationTestException($"Validator {includedValidator.Name} is not included");
	}
}
```

(using a local function rather than a linq query as I think it's easier to read)
