### ISSUE TITLE
Support IDictionary with RuleForEach

### ISSUE THREAD

**Issue by rcdailey** [FluentValidation/FluentValidation#2099]
### Is your feature request related to a problem? Please describe.

I have the following model (used for YAML deserialization):

```cs
public record MyYamlData
{
    public IDictionary<string, MyOtherObject>? MyObjects { get; init; }
}
```

And I want to be able to set validators for the values of each key value pair in the dictionary:

```cs
[UsedImplicitly]
public class MyOtherObjectValidator : CustomValidator<MyOtherObject>
{
    public MyOtherObjectValidator()
    {
        // ...
    }
}

internal class MyYamlDataValidator : AbstractValidator<MyYamlData>
{
    public MyYamlDataValidator()
    {
        RuleForEach(x => x.MyObjects).SetValidator(new MyOtherObjectValidator());
    }
}
```

However, the above call to `SetValidator` will not compile due to the `KeyValuePair` being in the mix.

### Describe the solution you'd like

I'd like:

- Native support for `IDictionary` in `RuleForEach()` so that the end result is effectively the same as `x.MyObjects.Select(y => y.Value)`.
- Support for the nullable dictionary member, such that if it is null, `SetValidator()` behaves as if it is operating on a non-nullable, empty collection. (e.g. something equivalent to `x.MyObjects?.Select(y => y.Value) ?? Array.Empty<T>()`).

### Describe alternatives you've considered

Solutions I've tried:

- I've tried creating my own implementation of `RuleForEach()` but this gets complicated, and `CollectionPropertyRule` is internal so I can't extend it (assuming that would even help; this was all experimentation on my part).
- Something like `RuleForEach(x => x.MyObjects.Select(y => y.Value)).SetValidator(...)` seems to compile but I didn't run tests to see if it would work. This code actually gets a bit nastier when I throw NRT in the mix for the `MyObjects` property.
- `TransformForEach(x => x.MyObjects, x => x.Value)` seems to compile (didn't test) but it is marked obsolete.

Solutions I do not want:

- Modifying the `AbstractValidator` to take `KeyValuePair`. The fact that a dictionary is in use is an implementation detail and I do not want to expose that in my validator definitions.

### Additional Context

I did find issue #593, but it's about 6 years old and locked. Plus I think my situation might be a bit different. Figure this is at least worth revisiting.

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion but this isn't something we intend to support. 

The purpose of `RuleForEach` is to support data sources that implement `IEnumerable<T>`, so your child validator would need to be for `AbstractValidator<KeyValuePair<string, MyOtherObject>>`, in the same way that when you use a regular C# `foreach` statement against a dictionary you receive a `KeyValuePair` to act upon. FluentValidation's `RuleForEach` mirrors this - each element being validated is the KeyValuePair, not the value. This is by design.

If you only want to validate the values of the dictionary you have 2 options:

- As you pointed out you could use `RuleForEach(x => x.MyObjects.Select(y => y.Value)).SetValidator(...)`, but the downside of this is it bypasses our expression tree cache by including a method call in the rule statement. 
- Introduce a surrogate property on your model and validate this directly. This is the recommended approach - FluentValidation is intended to validate properties of objects, not to perform data transformations for you.

```csharp
public record MyYamlData
{
    public IDictionary<string, MyOtherObject>? MyObjects { get; init; }

    // Introduce a surrogate property and define the rule against this instead.
    // You may want to consider caching this
    public IEnumerable<MyOtherObject> MyObjectValues => MyObjects.Select(y => y.Value);
}
```

FluentValidation

**Comment by rcdailey** [comment]
I like your second idea. Thank you for taking the time to respond!
