### ISSUE TITLE
Make full property path more accessible

### ISSUE THREAD

**Issue by rez-gparker** [FluentValidation/FluentValidation#2132]
### Is your feature request related to a problem? Please describe.

We need to use the full property path for the display name globally.  I know that you can create an extension method `WithFullName()` like this guy did https://github.com/FluentValidation/FluentValidation/issues/1906#issuecomment-1061197561.  Doing that, however, would require me to add `WithFullName()` after EVERY RULE in every validator which stinks.

For example:
```
RuleFor(x => x.FirstName).NotNull().WithFullName();
RuleFor(x => x.LastName).NotNull().WithFullName();
RuleFor(x => x.Whatever).NotNull().WithFullName();
RuleFor(x => x.Whatever2).NotNull().WithFullName();
```
`ValidatorOptions.Global.DisplayNameResolver` would have been the perfect place to fix my problem, but it does not provide the property path.  It would be super easy to add it there, but that would be a breaking change.

### Describe the solution you'd like

- Add full property path to ValidatorOptions.Global.DisplayNameResolver
- Add full property path as a placeholder to make it easily accessible in messages.  I.e., {FullPropertyName}
- Add an extension method to get full property path so we don't have to write our own.  Ie, "WithFullName"
- Add a property to the AbstractValidator that we can set so that all of it's rules use the full property path as the display name.  Call it "UsePropertyPathAsDisplayName" maybe?

### Describe alternatives you've considered

I came up with solution, but it is ugly.  I'm hoping I can throw this monstrosity away and that there is a simple solution that I was unaware of.  Note:  I am a FluentValidation newbie.  I am sure this is not what the ValidatorSelectors are for, but it was the only place I could find to hook in.  To use it, you just call this:

```
ValidatorOptions.Global.UsePropertyPathAsDisplayName();
```

Here is my workaround:

```
namespace FluentValidation;

using System.Collections.Concurrent;
using FluentValidation.Internal;

internal static class ValidatorConfigurationExtensions
{
    public static void UsePropertyPathAsDisplayName(this ValidatorConfiguration config)
    {
        ArgumentNullException.ThrowIfNull(config);
        var x = ValidatorOptions.Global.ValidatorSelectors;
        if (x.DefaultValidatorSelectorFactory is var def) x.DefaultValidatorSelectorFactory = () => new ValidatorSelectorWrapper(def());
        if (x.RulesetValidatorSelectorFactory is var ruleset) x.RulesetValidatorSelectorFactory = x => new ValidatorSelectorWrapper(ruleset(x));
        if (x.MemberNameValidatorSelectorFactory is var memberName) x.MemberNameValidatorSelectorFactory = x => new ValidatorSelectorWrapper(memberName(x));
        if (x.CompositeValidatorSelectorFactory is var composite) x.CompositeValidatorSelectorFactory = x => new ValidatorSelectorWrapper(composite(x));
    }
}

file class ValidatorSelectorWrapper : IValidatorSelector
{
    private readonly IValidatorSelector selector;
    private static readonly ConcurrentDictionary<Type, bool> cache = new();
    private const string InterfaceName = "IValidationRule`2";

    public ValidatorSelectorWrapper(IValidatorSelector selector) => this.selector = selector;

    public bool CanExecute(IValidationRule rule, string propertyPath, IValidationContext context)
    {
        if (cache.GetOrAdd(rule.GetType(), type => type.GetInterface(InterfaceName) is not null))
        {
            SetDisplayName((dynamic)rule, propertyPath);
        }

        return selector.CanExecute(rule, propertyPath, context);
    }

    private static void SetDisplayName<T, TProperty>(IValidationRule<T, TProperty> rule, string name) =>
        rule.SetDisplayName(name);
}
```

**Comment by JeremySkinner** [comment]
As I mentioned in the other issue that you linked to, the display name is intended to be user-readable, which is why it doesn't contain the full property path. If you really want to do this, then using an extension method is the correct/valid approach to take.  

> ValidatorOptions.Global.DisplayNameResolver would have been the perfect place to fix my problem, but it does not provide the property path. It would be super easy to add it there, but that would be a breaking change.

No, it is not super easy to add it here. The full property path is only constructed when validation occurs, as it relies on information about the object being validated (eg indexers etc) - it's dynamic. The display name resolver must support standalone execution, outside of a validation run. This is needed in order to provide metadata for UI libraries (for example, ASP.NET's clientside validation), where it's necessary to obtain the failure message without invoking the validator. This is why the DisplayName resolver only has access to information from when the validator is constructed (type, member & expression), but not runtime contextual information.

>  Doing that, however, would require me to add WithFullName() after EVERY RULE in every validator which stinks.

FluentValidation encourages explicitness over automatic/magic changes to default behaviour. An explicit call for every rule is recommended, as it's then very clear you're overriding the default behaviour with something nonstandard. If you think this "stinks" then you're welcome to use a different library.
