### ISSUE TITLE
Add a `PropertyPath` placeholder

### ISSUE THREAD

**Issue by JeremySkinner** [FluentValidation/FluentValidation#2134]
### Is your feature request related to a problem? Please describe.

Allow access to the full property path inside error message templates.

### Describe the solution you'd like

- Deprecate `ValidationContext.PropertyName` 
- Add `ValidationContext.PropertyPath` as a better-named replacement
- Add this as a message placeholder within `RuleBase.PrepareMessageFormatterForValidationError`

**Comment by rez-gparker** [comment]
Thank you for adding this. I think it will be a nice addition.

I cannot reply to https://github.com/FluentValidation/FluentValidation/issues/2132 because it is locked, but I just wanted to say this is an awesome library and I doubt there is a better one out there.  So, forgive my poor choice of words when I said that having to add WithFullName to every rule stinks in previous post.

Also, are you sure adding PropertyPath to ValidatorOptions.Global.DisplayNameResolver would be difficult?  It looks like the full property path (variable `propertyName`) is set a couple of lines below the call to `GetDisplayName` here.  Could it not be set earlier and passed into GetDisplayName?

```
string displayName = GetDisplayName(context);

if (PropertyName == null && displayName == null) {
	//No name has been specified. Assume this is a model-level rule, so we should use empty string instead.
	displayName = string.Empty;
}

// Construct the full name of the property, taking into account overriden property names and the chain (if we're in a nested validator)
string propertyName = context.PropertyChain.BuildPropertyName(PropertyName ?? displayName);
```

**Comment by JeremySkinner** [comment]
> Also, are you sure adding PropertyPath to ValidatorOptions.Global.DisplayNameResolver would be difficult?

I am certain. As I explained in the other thread, the DisplayNameResolver needs to support being executed without a property path, which is why it's not passed in. There are several scenarios where this happens but the most common is for our integration with ASP.NET's client-side validation. We need to generate messages without invoking the validator. There is no validation context available in that scenario, no property path, no model being validated.

As an example, see https://github.com/FluentValidation/FluentValidation.AspNetCore/blob/3ab2baedddded12ed6727d598f7355264bcca31c/src/FluentValidation.AspNetCore/Adapters/CreditCardClientValidator.cs#L33 

The property name is being generated completely outside of a validation run - it can't rely on things that are only available during validation. So adding the property path as a parameter to DisplayNameResolver is not something that can happen.

**Comment by rez-gparker** [comment]
I see now.  Thank you for the explanation.

**Comment by JeremySkinner** [comment]
11.7.0 is now released with this change
