### ISSUE TITLE
Return calculated values from the customs validator to the custom message.

### ISSUE THREAD

**Issue by optionmaker** [FluentValidation/FluentValidation#2209]
### Is your feature request related to a problem? Please describe.

Hi,
We created a rule with a custom validator. The custom validator will do some calculation and determine the result is valid or not, however, we have no means to retrieve the calculated result or append it to the custom message.

### Describe the solution you'd like

This is our current rule implementation, the rule will validate 3 properties that total number of characters not more than a limit. It can work as expected but we would like to know the actual number of characters of 3 properties when they violate the rule. Appreciate if you can lead us to correct direction. Thanks.

`RuleFor(x => new
 {
     x.HIF,
     x.OSI,
     x.COC
 })
 .Must(x => custom_MaxLengthV17(x.HIF, x.OSI, x.COC)).WithErrorCode("MaxLength35")
 .WithMessage("Max length35 validation (total characters cannot exceed 216).")
 .WithName(x => nameof(x.HIF) + "," + nameof(x.OSI) + "," + nameof(x.COC));

     private bool custom_MaxLengthV17(string HIF, string OSI, string COC)
     {
         const int _maxlength = 160;
         int tot_length = 0;
         if (!string.IsNullOrEmpty(HIF))
         {
             tot_length += HIF.Length + 4;
             if (HIF.Length > 65)
                 tot_length += 1;
             if (HIF.Length > 130)
                 tot_length += 1;
         }
         if (!string.IsNullOrEmpty(OSI))
         {
             tot_length += OSI.Length + 4;
             if (OSI.Length > 65)
                 tot_length += 1;
             if (OSI.Length > 130)
                 tot_length += 1;
         }
         if (!string.IsNullOrEmpty(COC))
             tot_length += COC.Length + 4;
         return (tot_length <= _maxlength);
     }`

**Comment by JeremySkinner** [comment]
In your case it's probably better to use `Custom` rather than `Must`, as then you can generate the error message yourself ([docs](https://docs.fluentvalidation.net/en/latest/custom-validators.html#writing-a-custom-validator)) and this can contain anything you want.

For future reference, this is an issue tracker for bugs in the FluentValidation library only, [not for support or questions on usage](https://github.com/FluentValidation/FluentValidation/blob/a0eaeae3721a647c8f253c559271a7708fb97cc2/.github/CONTRIBUTING.md#general-support-feedback-and-discussions)

**Comment by optionmaker** [comment]
Thanks Jeremy.
