### ISSUE TITLE
OverridePropertyName to take parameter

### ISSUE THREAD

**Issue by HaotongCheng** [FluentValidation/FluentValidation#2227]
### Is your feature request related to a problem? Please describe.

I was trying  to override the property name to include the property Id.
So instead of "Deal[0].Applicant[0].Employment[0].Province" I want just "Province_{EmploymentId}"

 

### Describe the solution you'd like

I'm thinking maybe something like this:
 RuleFor(employment => employment.ProvinceDd).GreaterThan(0).OverridePropertyName(C => $"ProvinceDd_{C.EmploymentId}").WithMessage("Please select a Province." ).WithSeverity(Severity.Warning);

I've read https://github.com/FluentValidation/FluentValidation/issues/874 
So I understand maybe I couldn't do anything with the [], but is there any way to add the property Id inside the PropertyName?

I just started to use this library, apologize if this is a dumb question

**Comment by JeremySkinner** [comment]
Hi,

No I'm afraid this isn't supported.

FluentValidation has 2 different types of property names:
- The "display name". This appears within the error message and is the 'user friendly' version of the property name. This is overridden by calling `WithName` and *does* take a parameter ([see here](https://docs.fluentvalidation.net/en/latest/configuring.html#overriding-the-property-name))
- The "real property name". This indicates the full path of the property which the error message is associated with. This is overidden by calling `OverridePropertyName`, it does not take a parameter because it *must* be a constant string; it can't be dynamic. This should always match the real name of the property.
