### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by JeremySkinner** [FluentValidation/FluentValidation#820]
- [x] Missing validators on the validator list page.
- [ ] ~~Custom message builders~~ Edit: This is really hard to document, so I think I'll leave it as a hidden advanced feature
- [x] Advanced test extensions
- [x] Async
- [x] Make cascade mode clearer 
- [x] Note about root page model with aspnet web pages (as per #887)
- [x] `Otherwise`
- [x] Why the email validator is intentionally not 100% comprehensive, and why this is OK.
- [x] Make it more obvious that InjectValidator is only available when using automatic validation. 
- [x] Severity
- [x] State
- [x] ErrorCode

**Comment by MajeQafouri** [comment]
Thank you

**Comment by benmccallum** [comment]
Hi @JeremySkinner, as mentioned over on #999 you had it on the list to doco async PropertyValidator usage, but I don't see it here unless it was covered by the "Async" item which is checked but I've been unable to find anything on the docs site under [PropertyValidator](https://fluentvalidation.net/custom-validators#reusable-property-validators).

I wanted to get some confirmation that using the technique on #999 (putting GetAwaiter().GetResult() in the IsValid method) wouldn't cause blocking. My knowledge in this area would suggest it could lead to deadlocks, but I'd love to be proven wrong as otherwise I'm not sure how to workaround this right now.

**Comment by JeremySkinner** [comment]
@benmccallum please open a separate issue explaining clearly what you’re trying to achieve and the problem you’re running into. This issue is a todo list for doc updates I need to write.

**Comment by SeanKilleen** [comment]
@JeremySkinner since we've checked off Severity, State ,and error codes, do you want to provide a little insight into what you mean by custom message builders? If so, I can run with it.

**Comment by SeanKilleen** [comment]
Also, should this have a 9.0 milestone?

**Comment by JeremySkinner** [comment]
> Also, should this have a 9.0 milestone?

No these are just ongoing doc updates, not necessarily related to 9. the ones that are are already in the 9.0 milestone #1405 and #981 

> do you want to provide a little insight into what you mean by custom message builders

Yes its an internal API feature that allows users to completely customize the process of generating the error message, and can be set using the `MessageBuilder` property on the rule. Here's an example of how i've suggested using it before: 

https://github.com/FluentValidation/FluentValidation/issues/1353#issuecomment-604951897
